import { useState, useRef, useEffect, useCallback } from 'react';
import Markdown from 'react-markdown';
import { useSubtitleStore } from '@/lib/stores/subtitle-store';
import { useMemoStore } from '@/lib/stores/memo-store';
import { normalizeTranscript, toSRT, toTXT, downloadFile, formatTimestamp } from '@/lib/subtitle-parser';
import { sendMessage } from '@/lib/messaging';
import type { SubtitleSegment, SubtitleTrackOption } from '@/lib/types';
import type { OutputLanguageCode } from '@/lib/output-language';
import { useUiText } from '@/lib/ui-text';

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`)
    .replace(/\n{2,}/g, '</p><p>')
    .replace(/^(?!<[hul])/gm, (line) => line ? `<p>${line}</p>` : '')
    .replace(/<p><\/p>/g, '');
}

interface Props {
  segments: SubtitleSegment[];
  targetLanguage: OutputLanguageCode;
}

const DOWNLOAD_OPTIONS = [
  { key: 'srt', labelKey: 'summary.download.srt' },
  { key: 'txt', labelKey: 'summary.download.txt' },
  { key: 'txt-no-ts', labelKey: 'summary.download.txtNoTs' },
] as const;

type DownloadFormat = typeof DOWNLOAD_OPTIONS[number]['key'];
type FallbackDownloadTrack = {
  id: string;
  label: string;
  languageCode: string;
  isAutoGenerated: false;
  fetchUrl: '';
  source: 'fallback';
};
type DownloadTrack = SubtitleTrackOption | FallbackDownloadTrack;

export function SummarySection({ segments, targetLanguage }: Props) {
  const { videoTitle, videoId, sourceSegments, subtitleTracks, currentTime } = useSubtitleStore();
  const { memos, createMemo, removeMemo } = useMemoStore();
  const ui = useUiText();
  const filename = videoTitle || videoId;
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const [collapsed, setCollapsed] = useState(false);
  const [selectedTrackId, setSelectedTrackId] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  // Memo quick-add state
  const [memoOpen, setMemoOpen] = useState(false);
  const [memoContent, setMemoContent] = useState('');
  const [memoSaving, setMemoSaving] = useState(false);
  const memoRef = useRef<HTMLDivElement>(null);

  // AI summary state
  const [summary, setSummary] = useState<string[]>([]);
  const [keywords, setKeywords] = useState<string[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const generatedForRef = useRef<string | null>(null);

  // Detailed summary state
  const [showDetailed, setShowDetailed] = useState(false);
  const [detailedSummary, setDetailedSummary] = useState<string | null>(null);
  const [isDetailedLoading, setIsDetailedLoading] = useState(false);
  const detailedKeyRef = useRef<string | null>(null);

  // Generate summary when segments are available
  useEffect(() => {
    if (segments.length === 0) return;

    // Create a stable key to avoid re-generating for the same content
    const key = `${videoId}-${targetLanguage}-${segments.length}`;
    if (generatedForRef.current === key) return;
    generatedForRef.current = key;

    const generate = async () => {
      setIsGenerating(true);
      setError(null);
      setSummary([]);
      setKeywords([]);

      try {
        const text = segments.map((s) => s.text).join(' ');
        const lang = segments[0]?.lang || 'en';
        const result = await sendMessage('generateSummary', { videoId, text, lang, targetLanguage });
        setSummary(result.summary);
        setKeywords(result.keywords);
      } catch (e) {
        const msg = e instanceof Error ? e.message : ui.t('failedSummary');
        setError(msg);
      } finally {
        setIsGenerating(false);
      }
    };

    generate();
  }, [segments, targetLanguage, videoId]);

  // Fetch detailed summary on toggle
  useEffect(() => {
    if (!showDetailed || segments.length === 0 || !videoId) return;

    const key = `${videoId}-${targetLanguage}-${segments.length}`;
    if (detailedKeyRef.current === key) return;
    detailedKeyRef.current = key;

    setIsDetailedLoading(true);
    const text = segments.map((s) => s.text).join(' ');
    const lang = segments[0]?.lang || 'en';
    sendMessage('generateDetailedSummary', { videoId, text, lang, targetLanguage })
      .then((result) => setDetailedSummary(result.detailedSummary))
      .catch((e) => {
        detailedKeyRef.current = null;
      })
      .finally(() => setIsDetailedLoading(false));
  }, [showDetailed, segments, videoId, targetLanguage]);

  // Reset detailed summary on video change
  useEffect(() => {
    setShowDetailed(false);
    setDetailedSummary(null);
    detailedKeyRef.current = null;
  }, [videoId]);

  const handleRetry = () => {
    const key = `${videoId}-${targetLanguage}-${segments.length}`;
    generatedForRef.current = null;
    setError(null);
    setSummary([]);
    setKeywords([]);
    setIsGenerating(true);

    const text = segments.map((s) => s.text).join(' ');
    const lang = segments[0]?.lang || 'en';
    sendMessage('generateSummary', { videoId, text, lang, targetLanguage })
      .then((result) => {
        setSummary(result.summary);
        setKeywords(result.keywords);
        generatedForRef.current = key;
      })
      .catch((e) => {
        const msg = e instanceof Error ? e.message : ui.t('failedSummary');
        setError(msg);
      })
      .finally(() => setIsGenerating(false));
  };

  const fallbackTrack: FallbackDownloadTrack | null = sourceSegments.length > 0
    ? {
        id: 'fallback-original',
        label: ui.t('originalSubtitles'),
        languageCode: sourceSegments[0]?.lang || '',
        isAutoGenerated: false,
        fetchUrl: '',
        source: 'fallback',
      }
    : null;
  const availableTracks: DownloadTrack[] = [
    ...(fallbackTrack ? [fallbackTrack] : []),
    ...subtitleTracks,
  ];
  const selectedTrack = availableTracks.find((track) => track.id === selectedTrackId) ?? availableTracks[0] ?? null;

  useEffect(() => {
    setSelectedTrackId(null);
    setDownloadError(null);
  }, [videoId]);

  useEffect(() => {
    if (availableTracks.length > 0 && (!selectedTrackId || !availableTracks.some((track) => track.id === selectedTrackId))) {
      setSelectedTrackId(availableTracks[0].id);
    }
  }, [availableTracks, selectedTrackId]);

  const handleDownload = async (format: DownloadFormat) => {
    if (!selectedTrack) {
      return;
    }

    setIsDownloading(true);
    setDownloadError(null);

    try {
      const downloadSegments = selectedTrack.source === 'fallback'
        ? sourceSegments
        : normalizeTranscript((await withTimeout(
            sendMessage('fetchSubtitleTrack', { videoId, track: selectedTrack }),
            40000,
            'Timed out while downloading subtitles.',
          )).segments);

      if (downloadSegments.length === 0) {
        throw new Error(ui.t('summary.download.noTracks'));
      }

      const targetFilename = createDownloadFilename(filename, selectedTrack, format);
      if (format === 'srt') {
        downloadFile(toSRT(downloadSegments), targetFilename, 'text/srt');
      } else if (format === 'txt') {
        downloadFile(toTXT(downloadSegments, true), targetFilename, 'text/plain');
      } else {
        downloadFile(toTXT(downloadSegments, false), targetFilename, 'text/plain');
      }
      setOpen(false);
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : ui.t('summary.download.failed'));
    } finally {
      setIsDownloading(false);
    }
  };

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    const root = menuRef.current?.getRootNode() as Document | ShadowRoot;
    const target = root ?? document;
    target.addEventListener('mousedown', handler as EventListener);
    return () => target.removeEventListener('mousedown', handler as EventListener);
  }, [open]);

  useEffect(() => {
    if (!memoOpen) return;
    const handler = (e: MouseEvent) => {
      if (memoRef.current && !memoRef.current.contains(e.target as Node)) {
        setMemoOpen(false);
      }
    };
    const root = memoRef.current?.getRootNode() as Document | ShadowRoot;
    const target = root ?? document;
    target.addEventListener('mousedown', handler as EventListener);
    return () => target.removeEventListener('mousedown', handler as EventListener);
  }, [memoOpen]);

  return (
    <div className="flex flex-col gap-3">
      {/* AI 요약 카드 */}
      <div className="ai-card-glow rounded-xl p-4">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="flex items-center justify-between w-full"
        >
          <div className="flex items-center gap-2">
            <svg className={`w-4 h-4 text-accent-brand ${isGenerating ? 'animate-pulse-soft' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.712L18 9.75l-.259-1.038a3.375 3.375 0 00-2.453-2.453L14.25 6l1.038-.259a3.375 3.375 0 002.453-2.453L18 2.25l.259 1.038a3.375 3.375 0 002.453 2.453L21.75 6l-1.038.259a3.375 3.375 0 00-2.453 2.453z" />
            </svg>
            <span className="text-[11px] font-bold text-accent-brand uppercase tracking-wider">{ui.t('summary.title')}</span>
          </div>
          <svg className={`w-3.5 h-3.5 text-text-muted transition-transform duration-200 ${collapsed ? '' : 'rotate-180'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        <div className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${collapsed ? 'grid-rows-[0fr]' : 'grid-rows-[1fr]'}`}>
          <div className="overflow-hidden">
          <div className="mt-2">
            {/* Loading state */}
            {isGenerating && (
              <div className="space-y-2">
                <div className="h-3 bg-border-subtle rounded animate-pulse w-full" />
                <div className="h-3 bg-border-subtle rounded animate-pulse w-5/6" />
                <div className="h-3 bg-border-subtle rounded animate-pulse w-4/6" />
              </div>
            )}

            {/* Error state */}
            {error && !isGenerating && (
              <div className="flex items-center gap-2">
                <p className="text-sm text-red-500">{error}</p>
                <button
                  onClick={handleRetry}
                  className="text-xs text-accent-brand hover:underline font-medium shrink-0"
                >
                  {ui.t('retry')}
                </button>
              </div>
            )}

            {/* Summary content */}
            {!isGenerating && !error && summary.length > 0 && (
              <ol className="space-y-1.5 list-none">
                {summary.map((line, i) => (
                  <li key={i} className="text-sm text-text-secondary leading-relaxed flex gap-2">
                    <span className="text-accent-brand mt-0.5 shrink-0 font-semibold text-xs">{i + 1}.</span>
                    <span>{line}</span>
                  </li>
                ))}
              </ol>
            )}

            {/* Idle state (no segments yet) */}
            {!isGenerating && !error && summary.length === 0 && (
              <p className="text-sm text-text-secondary leading-relaxed">
                {ui.t('summary.loading')}
              </p>
            )}

            {/* Keywords */}
            <div className="mt-4 flex gap-2 overflow-x-auto no-scrollbar">
              {!isGenerating && keywords.length > 0
                ? keywords.slice(0, 3).map((kw, i) => (
                    <span
                      key={i}
                      className="shrink-0 px-2.5 py-1 bg-white/50 backdrop-blur-sm rounded-lg text-[10px] text-accent-brand font-bold"
                    >
                      #{kw}
                    </span>
                  ))
                : isGenerating
                  ? null
                  : (
                    <>
                      <span className="shrink-0 px-2.5 py-1 bg-white/50 backdrop-blur-sm rounded-lg text-[10px] text-accent-brand font-bold">#keywords</span>
                      <span className="shrink-0 px-2.5 py-1 bg-white/50 backdrop-blur-sm rounded-lg text-[10px] text-accent-brand font-bold">#summarizing</span>
                    </>
                  )}
            </div>

            {/* Detailed summary toggle */}
            {!isGenerating && !error && summary.length > 0 && (
              <div className="mt-4">
                <button
                  onClick={() => setShowDetailed(!showDetailed)}
                  className="flex items-center gap-1.5 text-[11px] font-bold text-accent-brand hover:opacity-80 transition-opacity"
                >
                  <svg className={`w-3.5 h-3.5 transition-transform duration-300 ${showDetailed ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M19 9l-7 7-7-7" />
                  </svg>
                  {showDetailed ? ui.t('summary.showLess') : ui.t('summary.showMore')}
                </button>

                <div className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${showDetailed ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}>
                  <div className="overflow-hidden">
                    <div className="mt-4 pt-4 bg-white/30 rounded-xl p-3">
                      <div className="max-h-[40vh] overflow-y-auto pr-2 custom-scrollbar">
                        {isDetailedLoading && (
                          <div className="space-y-3">
                            <div className="h-3 bg-white/50 rounded-full animate-pulse w-full" />
                            <div className="h-3 bg-white/50 rounded-full animate-pulse w-5/6" />
                            <div className="h-3 bg-white/50 rounded-full animate-pulse w-4/6" />
                          </div>
                        )}
                        {!isDetailedLoading && detailedSummary && (
                          <div className="chat-markdown text-sm text-text-secondary leading-relaxed font-medium">
                            <Markdown>{detailedSummary}</Markdown>
                          </div>
                        )}
                      </div>
                      {!isDetailedLoading && detailedSummary && (
                        <DetailedSummaryToolbar markdown={detailedSummary} videoTitle={videoTitle || videoId} />
                      )}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
          </div>
        </div>
      </div>

      {/* 액션 버튼들 */}
      <div className="flex gap-2.5">
        <div ref={menuRef} className="relative flex-1">
          <button
            onClick={() => setOpen(!open)}
            className="btn-secondary w-full justify-between gap-2 h-10 text-xs font-bold"
          >
            <div className="flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5 5-5M12 15V3" />
              </svg>
              {ui.t('summary.download')}
            </div>
            <svg className={`w-3.5 h-3.5 transition-transform duration-300 ${open ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>

        {open && (
          <div className="absolute left-0 right-0 mt-2 py-2 bg-white rounded-2xl shadow-2xl animate-fade-in z-30 overflow-hidden ring-1 ring-black/5">
            <div className="px-4 pt-2 pb-1 text-[10px] font-bold uppercase tracking-wider text-text-muted">
              {ui.t('summary.download.selectTrack')}
            </div>
            {availableTracks.length === 0 && (
              <div className="px-4 py-3 text-xs text-text-muted font-medium">
                {ui.t('summary.download.noTracks')}
              </div>
            )}
            <div className="max-h-48 overflow-y-auto">
              {availableTracks.map((track) => (
                <button
                  key={track.id}
                  onClick={() => setSelectedTrackId(track.id)}
                  className={`w-full px-4 py-2.5 text-xs text-left transition-all flex items-center justify-between gap-3 ${
                    selectedTrack?.id === track.id
                      ? 'bg-accent/5 text-accent-brand'
                      : 'text-text-secondary hover:bg-bg-subtle hover:text-text-primary'
                  }`}
                >
                  <div className="min-w-0">
                    <div className="truncate font-bold">{track.label}</div>
                    <div className="mt-0.5 text-[10px] text-text-muted font-medium">
                      {track.isAutoGenerated ? ui.t('summary.download.autoGenerated') : ui.t('summary.download.manual')}
                      {track.languageCode ? ` · ${track.languageCode}` : ''}
                    </div>
                  </div>
                  <span className="shrink-0">
                    {selectedTrack?.id === track.id ? <CheckIcon /> : ''}
                  </span>
                </button>
              ))}
            </div>
            <div className="my-1.5 h-px bg-bg-elevated mx-2" />
            <div className="px-4 pt-1 pb-1 text-[10px] font-bold uppercase tracking-wider text-text-muted">
              {ui.t('summary.download.selectFormat')}
            </div>
            {DOWNLOAD_OPTIONS.map((opt) => (
              <button
                key={opt.key}
                disabled={!selectedTrack || isDownloading}
                onClick={() => void handleDownload(opt.key)}
                className="w-full px-4 py-2.5 text-xs text-left text-text-secondary font-bold hover:bg-bg-subtle hover:text-text-primary transition-all flex items-center justify-between group disabled:cursor-not-allowed disabled:opacity-50"
              >
                {ui.t(opt.labelKey)}
                <svg className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 group-hover:translate-x-0.5 transition-all" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path d="M9 5l7 7-7 7" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>
            ))}
            {downloadError && (
              <p className="px-4 py-2 text-[11px] text-red-500 font-medium">
                {downloadError}
              </p>
            )}
          </div>
        )}
        </div>

        <div ref={memoRef} className="relative">
          <button
            onClick={() => setMemoOpen(!memoOpen)}
            className="shrink-0 h-10 px-4 text-xs font-bold rounded-xl bg-violet-600 text-white hover:bg-violet-700 active:scale-[0.97] transition-all flex items-center gap-2 shadow-sm shadow-violet-200"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 5v14M5 12h14" />
            </svg>
            {ui.t('memo.new')}
          </button>

          {memoOpen && (
            <div className="absolute right-0 mt-2 w-80 p-4 bg-white rounded-2xl shadow-2xl animate-fade-in z-30 ring-1 ring-black/5 flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold text-text-primary uppercase tracking-wider">{ui.t('memo.new')}</span>
                <span className="text-[10px] font-bold text-violet-600 bg-violet-50 px-2 py-0.5 rounded-lg">
                  {formatTimestamp(currentTime)}
                </span>
              </div>
              <textarea
                value={memoContent}
                onChange={(e) => setMemoContent(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    if (memoContent.trim() && videoId) {
                      setMemoSaving(true);
                      void createMemo(videoId, currentTime, memoContent.trim(), videoTitle || undefined).then(() => {
                        setMemoContent('');
                        setMemoSaving(false);
                      });
                    }
                  }
                }}
                placeholder={ui.t('memo.placeholder')}
                rows={3}
                className="w-full px-3 py-2.5 text-sm bg-bg-subtle rounded-xl resize-none text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-violet-100 font-medium"
                autoFocus
              />
              <div className="flex justify-end mt-1">
                <button
                  onClick={() => {
                    if (!memoContent.trim() || !videoId) return;
                    setMemoSaving(true);
                    void createMemo(videoId, currentTime, memoContent.trim(), videoTitle || undefined).then(() => {
                      setMemoContent('');
                      setMemoSaving(false);
                    });
                  }}
                  disabled={!memoContent.trim() || memoSaving}
                  className="h-8 px-4 text-xs font-bold rounded-lg bg-violet-600 text-white hover:bg-violet-700 disabled:opacity-50 transition-all active:scale-[0.97]"
                >
                  {ui.t('common.save')}
                </button>
              </div>

              {memos.length > 0 && (
                <>
                  <div className="h-px bg-bg-elevated my-1" />
                  <div className="flex flex-col gap-2 max-h-48 overflow-y-auto pr-1 custom-scrollbar">
                    {memos.map((memo) => (
                      <div key={memo.id} className="p-3 bg-bg-subtle/50 rounded-xl group relative transition-all hover:bg-bg-subtle/80">
                        <div className="flex items-center justify-between mb-1.5">
                          <span className="text-[10px] font-bold text-text-muted bg-white px-1.5 py-0.5 rounded shadow-sm">
                            {formatTimestamp(memo.timestamp)}
                          </span>
                          <button
                            onClick={() => {
                              if (videoId) {
                                void removeMemo(videoId, memo.id);
                              }
                            }}
                            className="opacity-0 group-hover:opacity-100 text-[10px] text-red-400 hover:text-red-500 font-bold transition-all"
                          >
                            {ui.t('common.delete')}
                          </button>
                        </div>
                        <p className="text-xs text-text-secondary leading-relaxed whitespace-pre-wrap font-medium">
                          {memo.content}
                        </p>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function DetailedSummaryToolbar({ markdown, videoTitle }: { markdown: string; videoTitle: string }) {
  const ui = useUiText();
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const showCopied = (key: string) => {
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 1500);
  };

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(markdown);
    showCopied('md');
  };

  const handleCopyRichText = async () => {
    const html = markdownToHtml(markdown);
    await navigator.clipboard.write([
      new ClipboardItem({
        'text/html': new Blob([html], { type: 'text/html' }),
        'text/plain': new Blob([markdown], { type: 'text/plain' }),
      }),
    ]);
    showCopied('rich');
  };

  const handleExportObsidian = () => {
    const title = sanitizeFilenamePart(videoTitle) || 'YouTube Summary';
    const uri = `obsidian://new?name=${encodeURIComponent(title)}&content=${encodeURIComponent(markdown)}`;
    window.open(uri, '_blank');
  };

  const handleDownloadMd = () => {
    const title = sanitizeFilenamePart(videoTitle) || 'summary';
    downloadFile(markdown, `${title}.md`, 'text/markdown');
  };

  const btnClass = 'flex items-center gap-1.5 px-2.5 py-1.5 text-[10px] font-bold rounded-lg transition-all';
  const defaultClass = `${btnClass} text-text-muted hover:text-text-primary hover:bg-white/50`;
  const copiedClass = `${btnClass} text-emerald-600 bg-emerald-50`;

  return (
    <div className="mt-3 pt-3 flex flex-wrap gap-1.5">
      <button onClick={handleCopyMarkdown} className={copiedKey === 'md' ? copiedClass : defaultClass}>
        {copiedKey === 'md' ? (
          <><CheckIcon />{ui.t('summary.export.copied')}</>
        ) : (
          <><MarkdownIcon />{ui.t('summary.export.markdown')}</>
        )}
      </button>
      <button onClick={handleCopyRichText} className={copiedKey === 'rich' ? copiedClass : defaultClass}>
        {copiedKey === 'rich' ? (
          <><CheckIcon />{ui.t('summary.export.copied')}</>
        ) : (
          <><ClipboardIcon />{ui.t('summary.export.richText')}</>
        )}
      </button>
      <button onClick={handleExportObsidian} className={defaultClass}>
        <ObsidianIcon />{ui.t('summary.export.obsidian')}
      </button>
      <button onClick={handleDownloadMd} className={defaultClass}>
        <DownloadIcon />{ui.t('summary.export.download')}
      </button>
    </div>
  );
}

function CheckIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function MarkdownIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M2 4h20v16H2z" />
      <path d="M6 8v8l3-3 3 3V8" />
      <path d="M18 16l-2-4-2 4" />
    </svg>
  );
}

function ClipboardIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function ObsidianIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 2L2 7l10 5 10-5-10-5z" />
      <path d="M2 17l10 5 10-5" />
      <path d="M2 12l10 5 10-5" />
    </svg>
  );
}

function DownloadIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  );
}

function createDownloadFilename(filename: string, track: DownloadTrack, format: DownloadFormat) {
  const suffix = [track.languageCode, track.isAutoGenerated ? 'auto' : '']
    .filter(Boolean)
    .map((value) => sanitizeFilenamePart(value))
    .filter(Boolean)
    .join('.');
  const extension = format === 'srt' ? 'srt' : 'txt';
  return suffix ? `${filename}.${suffix}.${extension}` : `${filename}.${extension}`;
}

function sanitizeFilenamePart(value: string) {
  return value.replace(/[\\/:*?"<>|\s]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

function withTimeout<T>(promise: Promise<T>, timeoutMs: number, message: string): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = window.setTimeout(() => {
      reject(new Error(message));
    }, timeoutMs);

    promise
      .then((value) => {
        window.clearTimeout(timer);
        resolve(value);
      })
      .catch((error: unknown) => {
        window.clearTimeout(timer);
        reject(error);
      });
  });
}
