// youtube-transcript-plus 응답 기반
export interface TranscriptResponse {
  text: string;
  duration: number;
  offset: number;
  lang: string;
}

// 앱 내부 정규화된 자막 모델
export interface SubtitleSegment {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
  lang: string;
}

export interface SubtitleTrackOption {
  id: string;
  label: string;
  languageCode: string;
  isAutoGenerated: boolean;
  vssId?: string;
  playerTrackData?: Record<string, unknown>;
  fetchUrl: string;
  source: 'youtube' | 'invidious';
}

// AI 타임라인 항목 (F-003 placeholder)
export interface TimelineItem {
  timestamp: number;
  summary: string;
  importance: number;
}

// AI 아티클 섹션 (F-004 placeholder)
export interface ArticleSection {
  topicTitle: string;
  description: string;
  startTimestamp: number;
  endTimestamp: number;
}

// 메모 (F-006)
export interface Memo {
  id: string;
  videoId: string;
  videoTitle?: string;
  timestamp: number;
  content: string;
  createdAt: string;
  updatedAt: string;
}

// 탭 타입
export type TabType = 'timeline' | 'article' | 'script' | 'chat';
