import {
  createContext,
  useContext,
  useMemo,
  type ReactNode,
} from 'react';
import type { OutputLanguageCode, OutputLanguageOption } from './output-language';

type TranslationKey =
  | 'language'
  | 'group.default'
  | 'group.global'
  | 'group.eastAsia'
  | 'group.indian'
  | 'group.european'
  | 'originalSubtitles'
  | 'refreshAi'
  | 'refreshing'
  | 'aiRetry'
  | 'clearSubtitleCache'
  | 'clearingSubtitleCache'
  | 'retry'
  | 'close'
  | 'tab.script'
  | 'tab.timeline'
  | 'tab.article'
  | 'tab.chat'
  | 'playVideo'
  | 'openYoutube'
  | 'failedSummary'
  | 'failedTimeline'
  | 'failedArticle'
  | 'failedLoadSubtitles'
  | 'failedTranslateSubtitles'
  | 'script.empty'
  | 'script.searchPlaceholder'
  | 'script.results'
  | 'script.segments'
  | 'script.autoScroll'
  | 'common.on'
  | 'common.off'
  | 'summary.title'
  | 'summary.showMore'
  | 'summary.showLess'
  | 'summary.export.markdown'
  | 'summary.export.richText'
  | 'summary.export.obsidian'
  | 'summary.export.download'
  | 'summary.export.copied'
  | 'summary.loading'
  | 'summary.download'
  | 'summary.download.srt'
  | 'summary.download.txt'
  | 'summary.download.txtNoTs'
  | 'summary.download.selectTrack'
  | 'summary.download.selectFormat'
  | 'summary.download.loadingTracks'
  | 'summary.download.noTracks'
  | 'summary.download.manual'
  | 'summary.download.autoGenerated'
  | 'summary.download.failed'
  | 'article.title'
  | 'article.description'
  | 'article.empty'
  | 'article.expandAll'
  | 'article.collapseAll'
  | 'common.copy'
  | 'common.export'
  | 'article.now'
  | 'timeline.title'
  | 'timeline.description'
  | 'timeline.empty'
  | 'timeline.core'
  | 'timeline.important'
  | 'timeline.point'
  | 'memo.new'
  | 'memo.placeholder'
  | 'common.save'
  | 'memo.empty'
  | 'common.edit'
  | 'common.delete'
  | 'common.cancel'
  | 'memo.export'
  | 'options.title'
  | 'options.language'
  | 'options.description'
  | 'options.outputLanguage'
  | 'options.currentSelection'
  | 'options.howItWorks'
  | 'options.rule1'
  | 'options.rule2'
  | 'options.rule3'
  | 'options.manageMemos'
  | 'memos.title'
  | 'memos.pageTitle'
  | 'memos.description'
  | 'memos.empty'
  | 'memos.videoMemos'
  | 'memos.deleteConfirm'
  | 'memos.totalCount'
  | 'memos.searchPlaceholder'
  | 'chat.placeholder'
  | 'chat.send'
  | 'chat.empty'
  | 'chat.error'
  | 'chat.suggestions'
  | 'chat.customPrompt'
  | 'chat.customPrompt.placeholder'
  | 'chat.customPrompt.description'
  | 'memo.openManager'
  | 'options.theme'
  | 'options.themeDescription'
  | 'options.theme.system'
  | 'options.theme.light'
  | 'options.theme.dark';

type TranslationDict = Record<TranslationKey, string>;

const EN_TRANSLATIONS: TranslationDict = {
  language: 'Language',
  'group.default': 'Default',
  'group.global': 'Global',
  'group.eastAsia': 'East Asia',
  'group.indian': 'Indian languages',
  'group.european': 'European languages',
  originalSubtitles: 'Original subtitles',
  refreshAi: 'Refresh AI',
  refreshing: 'Refreshing...',
  aiRetry: 'AI Retry',
  clearSubtitleCache: 'Clear subtitle cache',
  clearingSubtitleCache: 'Clearing cache...',
  retry: 'Retry',
  close: 'Close',
  'tab.script': 'Script',
  'tab.timeline': 'Timeline',
  'tab.article': 'Article',
  'tab.chat': 'AI Chat',
  playVideo: 'Play a video to get started',
  openYoutube: 'Open a YouTube video and AI will analyze the subtitles for you.',
  failedSummary: 'Failed to generate the summary.',
  failedTimeline: 'Failed to generate the timeline.',
  failedArticle: 'Failed to generate the article.',
  failedLoadSubtitles: 'Could not load subtitles.',
  failedTranslateSubtitles: 'Could not translate subtitles.',
  'script.empty': 'No subtitles found for this video.',
  'script.searchPlaceholder': 'Search transcript...',
  'script.results': '{count} results',
  'script.segments': '{count} segments',
  'script.autoScroll': 'Auto-scroll',
  'common.on': 'ON',
  'common.off': 'OFF',
  'summary.title': 'AI Insights',
  'summary.showMore': 'Show detailed summary',
  'summary.showLess': 'Hide detailed summary',
  'summary.export.markdown': 'Copy Markdown',
  'summary.export.richText': 'Copy for Notion',
  'summary.export.obsidian': 'Obsidian',
  'summary.export.download': 'Download .md',
  'summary.export.copied': 'Copied!',
  'summary.loading': 'Extracting key insights from this video. Please wait.',
  'summary.download': 'Download subtitles',
  'summary.download.srt': 'Subtitle file (SRT)',
  'summary.download.txt': 'Text (with timestamps)',
  'summary.download.txtNoTs': 'Text (content only)',
  'summary.download.selectTrack': 'Subtitle track',
  'summary.download.selectFormat': 'Format',
  'summary.download.loadingTracks': 'Loading subtitle options...',
  'summary.download.noTracks': 'No original subtitle tracks available.',
  'summary.download.manual': 'Manual',
  'summary.download.autoGenerated': 'Auto-generated',
  'summary.download.failed': 'Could not download subtitles.',
  'article.title': 'Article',
  'article.description': 'Content is grouped by topic, and each section can jump to its timestamp.',
  'article.empty': 'The article view will be generated once subtitles are ready.',
  'article.expandAll': 'Expand all',
  'article.collapseAll': 'Collapse all',
  'common.copy': 'Copy',
  'common.export': 'Export',
  'article.now': 'Now',
  'timeline.title': 'Timeline',
  'timeline.description': 'Important moments are organized chronologically, with the current point highlighted.',
  'timeline.empty': 'The timeline will appear once subtitles are ready.',
  'timeline.core': 'Core',
  'timeline.important': 'Important',
  'timeline.point': 'Point',
  'memo.new': 'New Memo',
  'memo.placeholder': 'Write your thoughts at this moment...',
  'common.save': 'Save',
  'memo.empty': 'No memos yet.',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.cancel': 'Cancel',
  'memo.export': 'Export all memos (.txt)',
  'options.title': 'Subtext Settings',
  'options.language': 'Language',
  'options.description': 'Choose the language used for translated subtitles, AI summaries, timeline items, and article views.',
  'options.outputLanguage': 'Output language',
  'options.currentSelection': 'Current selection: {label}',
  'options.howItWorks': 'How it works',
  'options.rule1': 'Translated subtitles follow this setting.',
  'options.rule2': 'AI summary, timeline, and article outputs follow the same language.',
  'options.rule3': 'Changing the setting applies automatically the next time the panel refreshes.',
  'options.manageMemos': 'Manage Memos',
  'memos.title': 'Memo Manager',
  'memos.pageTitle': 'Subtext — Memo Manager',
  'memos.description': 'View and manage memos from all videos in one place.',
  'memos.empty': 'No memos saved yet.',
  'memos.videoMemos': 'Video: {videoId}',
  'memos.deleteConfirm': 'Are you sure you want to delete this memo?',
  'memos.totalCount': '{count} memos',
  'memos.searchPlaceholder': 'Search memos...',
  'chat.placeholder': 'Ask about this video...',
  'chat.send': 'Send',
  'chat.empty': 'Ask a question about this video and AI will answer based on the subtitles.',
  'chat.error': 'Failed to get a response.',
  'chat.suggestions': 'Suggested questions',
  'chat.customPrompt': 'Custom prompt',
  'chat.customPrompt.placeholder': 'e.g. Answer in bullet points...',
  'chat.customPrompt.description': 'Add custom instructions for AI responses.',
  'memo.openManager': 'Memo Manager',
  'options.theme': 'Theme',
  'options.themeDescription': 'Choose your preferred appearance.',
  'options.theme.system': 'System',
  'options.theme.light': 'Light',
  'options.theme.dark': 'Dark',
};

const LOCALE_OVERRIDES: Partial<Record<OutputLanguageCode, Partial<TranslationDict>>> = {
  ko: {
    language: '언어',
    'group.default': '기본',
    'group.global': '글로벌',
    'group.eastAsia': '동아시아',
    'group.indian': '인도권 언어',
    'group.european': '유럽 언어',
    originalSubtitles: '원본 자막',
    refreshAi: 'AI 새로고침',
    refreshing: '새로고침 중...',
    aiRetry: 'AI 다시 생성',
    clearSubtitleCache: '자막 캐시 삭제',
    clearingSubtitleCache: '캐시 삭제 중...',
    retry: '다시 시도',
    close: '닫기',
    'tab.script': '스크립트',
    'tab.timeline': '타임라인',
    'tab.article': '아티클',
    'tab.chat': 'AI 채팅',
    playVideo: '영상을 재생해 시작하세요',
    openYoutube: 'YouTube 영상을 열면 AI가 자막을 분석합니다.',
    failedSummary: 'AI 요약을 생성하지 못했습니다.',
    failedTimeline: '타임라인을 생성하지 못했습니다.',
    failedArticle: '아티클을 생성하지 못했습니다.',
    failedLoadSubtitles: '자막을 불러오지 못했습니다.',
    failedTranslateSubtitles: '자막을 번역하지 못했습니다.',
    'script.empty': '이 영상의 자막을 찾을 수 없습니다.',
    'script.searchPlaceholder': '자막 검색...',
    'script.results': '{count}개 결과',
    'script.segments': '{count}개 세그먼트',
    'script.autoScroll': '자동 스크롤',
    'common.on': '켜짐',
    'common.off': '꺼짐',
    'summary.title': 'AI 인사이트',
    'summary.showMore': '상세 요약 보기',
    'summary.showLess': '상세 요약 접기',
    'summary.export.markdown': '마크다운 복사',
    'summary.export.richText': '노션용 복사',
    'summary.export.obsidian': 'Obsidian',
    'summary.export.download': '.md 다운로드',
    'summary.export.copied': '복사됨!',
    'summary.loading': '영상의 핵심 내용을 추출하는 중입니다. 잠시만 기다려주세요.',
    'summary.download': '자막 다운로드',
    'summary.download.srt': '자막 파일 (SRT)',
    'summary.download.txt': '텍스트 (타임스탬프 포함)',
    'summary.download.txtNoTs': '텍스트 (내용만)',
    'summary.download.selectTrack': '자막 트랙',
    'summary.download.selectFormat': '형식',
    'summary.download.loadingTracks': '자막 옵션을 불러오는 중입니다...',
    'summary.download.noTracks': '다운로드 가능한 원본 자막 트랙이 없습니다.',
    'summary.download.manual': '수동 자막',
    'summary.download.autoGenerated': '자동 생성',
    'summary.download.failed': '자막을 다운로드하지 못했습니다.',
    'article.title': '아티클',
    'article.description': '주제별로 내용을 묶고, 각 섹션에서 해당 시점으로 이동할 수 있습니다.',
    'article.empty': '자막이 준비되면 아티클 보기가 생성됩니다.',
    'article.expandAll': '모두 펼치기',
    'article.collapseAll': '모두 접기',
    'common.copy': '복사',
    'common.export': '내보내기',
    'article.now': '지금',
    'timeline.title': '타임라인',
    'timeline.description': '중요한 순간을 시간순으로 정리하고, 현재 위치를 강조합니다.',
    'timeline.empty': '자막이 준비되면 타임라인이 표시됩니다.',
    'timeline.core': '핵심',
    'timeline.important': '중요',
    'timeline.point': '포인트',
    'memo.new': '새 메모',
    'memo.placeholder': '지금 이 순간의 생각을 적어보세요...',
    'common.save': '저장',
    'memo.empty': '아직 메모가 없습니다.',
    'common.edit': '수정',
    'common.delete': '삭제',
    'common.cancel': '취소',
    'memo.export': '메모 전체 내보내기 (.txt)',
    'options.title': 'Subtext 설정',
    'options.language': '언어',
    'options.description': '번역 자막, AI 요약, 타임라인, 아티클 보기에 사용할 언어를 선택하세요.',
    'options.outputLanguage': '출력 언어',
    'options.currentSelection': '현재 선택: {label}',
    'options.howItWorks': '작동 방식',
    'options.rule1': '번역 자막은 이 설정을 따릅니다.',
    'options.rule2': 'AI 요약, 타임라인, 아티클도 같은 언어를 사용합니다.',
    'options.rule3': '설정을 바꾸면 다음 패널 갱신 시 자동으로 반영됩니다.',
    'options.manageMemos': '메모 관리',
    'memos.title': '메모 관리',
    'memos.pageTitle': 'Subtext — 메모 관리',
    'memos.description': '모든 영상의 메모를 한 곳에서 확인하고 관리합니다.',
    'memos.empty': '저장된 메모가 없습니다.',
    'memos.videoMemos': '영상: {videoId}',
    'memos.deleteConfirm': '이 메모를 삭제하시겠습니까?',
    'memos.totalCount': '{count}개의 메모',
    'memos.searchPlaceholder': '메모 검색...',
    'chat.placeholder': '이 영상에 대해 질문하세요...',
    'chat.send': '보내기',
    'chat.empty': '이 영상에 대해 질문하면 AI가 자막을 기반으로 답변합니다.',
    'chat.error': '응답을 받지 못했습니다.',
    'chat.suggestions': '추천 질문',
    'chat.customPrompt': '사용자 프롬프트',
    'chat.customPrompt.placeholder': '예: 요점을 정리해서 답변해줘...',
    'chat.customPrompt.description': 'AI 응답에 대한 사용자 지시를 추가합니다.',
    'memo.openManager': '메모 관리',
    'options.theme': '테마',
    'options.themeDescription': '원하는 화면 모드를 선택하세요.',
    'options.theme.system': '시스템',
    'options.theme.light': '라이트',
    'options.theme.dark': '다크',
  },
  ja: {
    language: '言語',
    'group.default': '既定',
    'group.global': 'グローバル',
    'group.eastAsia': '東アジア',
    'group.indian': 'インド言語',
    'group.european': 'ヨーロッパ言語',
    originalSubtitles: '元の字幕',
    refreshAi: 'AIを更新',
    refreshing: '更新中...',
    aiRetry: 'AIを再生成',
    retry: '再試行',
    close: '閉じる',
    'tab.script': 'スクリプト',
    'tab.timeline': 'タイムライン',
    'tab.article': '記事',
    'tab.chat': 'AIチャット',
    playVideo: '動画を再生して開始してください',
    openYoutube: 'YouTube動画を開くと、AIが字幕を分析します。',
    'script.empty': 'この動画の字幕は見つかりませんでした。',
    'script.searchPlaceholder': '字幕を検索...',
    'script.results': '{count} 件の結果',
    'script.segments': '{count} 個のセグメント',
    'script.autoScroll': '自動スクロール',
    'common.on': 'オン',
    'common.off': 'オフ',
    'summary.title': 'AIインサイト',
    'summary.showMore': '詳細な要約を表示',
    'summary.showLess': '詳細な要約を閉じる',
    'summary.export.markdown': 'Markdownをコピー',
    'summary.export.richText': 'Notion用にコピー',
    'summary.export.obsidian': 'Obsidian',
    'summary.export.download': '.mdダウンロード',
    'summary.export.copied': 'コピー済み！',
    'summary.loading': '動画の重要ポイントを抽出しています。しばらくお待ちください。',
    'summary.download': '字幕をダウンロード',
    'summary.download.srt': '字幕ファイル (SRT)',
    'summary.download.txt': 'テキスト (タイムスタンプ付き)',
    'summary.download.txtNoTs': 'テキスト (本文のみ)',
    'article.title': '記事',
    'article.description': '内容をトピックごとに整理し、各セクションから該当時刻へ移動できます。',
    'article.empty': '字幕の準備ができると記事ビューが生成されます。',
    'article.expandAll': 'すべて展開',
    'article.collapseAll': 'すべて折りたたむ',
    'common.copy': 'コピー',
    'common.export': '書き出し',
    'article.now': '現在',
    'timeline.title': 'タイムライン',
    'timeline.description': '重要な場面を時系列で整理し、現在位置を強調表示します。',
    'timeline.empty': '字幕の準備ができるとタイムラインが表示されます。',
    'timeline.core': '核心',
    'timeline.important': '重要',
    'timeline.point': 'ポイント',
    'memo.new': '新しいメモ',
    'memo.placeholder': 'この瞬間の考えを書いてください...',
    'common.save': '保存',
    'memo.empty': 'メモはまだありません。',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.cancel': 'キャンセル',
    'memo.export': 'すべてのメモを書き出し (.txt)',
    'options.title': 'Subtext設定',
    'options.language': '言語',
    'options.description': '翻訳字幕、AI要約、タイムライン、記事ビューに使う言語を選択します。',
    'options.outputLanguage': '出力言語',
    'options.currentSelection': '現在の選択: {label}',
    'options.howItWorks': '仕組み',
    'options.rule1': '翻訳字幕はこの設定に従います。',
    'options.rule2': 'AI要約、タイムライン、記事も同じ言語を使います。',
    'options.rule3': '設定を変更すると、次回パネル更新時に自動適用されます。',
    'options.manageMemos': 'メモ管理',
    'memos.title': 'メモ管理',
    'memos.pageTitle': 'Subtext — メモ管理',
    'memos.description': 'すべての動画のメモを一か所で確認・管理できます。',
    'memos.empty': '保存されたメモはありません。',
    'memos.videoMemos': '動画: {videoId}',
    'memos.deleteConfirm': 'このメモを削除しますか？',
    'memos.totalCount': '{count} 件のメモ',
    'memos.searchPlaceholder': 'メモを検索...',
    'chat.placeholder': 'この動画について質問してください...',
    'chat.send': '送信',
    'chat.empty': 'この動画について質問すると、AIが字幕を基に回答します。',
    'chat.error': '回答を取得できませんでした。',
    'chat.suggestions': 'おすすめの質問',
    'chat.customPrompt': 'カスタムプロンプト',
    'chat.customPrompt.placeholder': '例：箇条書きで回答してください...',
    'chat.customPrompt.description': 'AI応答へのカスタム指示を追加します。',
    'memo.openManager': 'メモ管理',
    'options.theme': 'テーマ',
    'options.themeDescription': 'お好みの表示モードを選択してください。',
    'options.theme.system': 'システム',
    'options.theme.light': 'ライト',
    'options.theme.dark': 'ダーク',
  },
  'zh-Hans': {
    language: '语言',
    'group.default': '默认',
    'group.global': '全球',
    'group.eastAsia': '东亚',
    'group.indian': '印度语言',
    'group.european': '欧洲语言',
    originalSubtitles: '原始字幕',
    refreshAi: '刷新 AI',
    refreshing: '刷新中...',
    aiRetry: '重新生成 AI',
    retry: '重试',
    close: '关闭',
    'tab.script': '脚本',
    'tab.timeline': '时间线',
    'tab.article': '文章',
    'tab.chat': 'AI聊天',
    playVideo: '播放视频以开始',
    openYoutube: '打开 YouTube 视频后，AI 会为你分析字幕。',
    'script.empty': '未找到此视频的字幕。',
    'script.searchPlaceholder': '搜索字幕...',
    'script.results': '{count} 个结果',
    'script.segments': '{count} 段',
    'script.autoScroll': '自动滚动',
    'common.on': '开',
    'common.off': '关',
    'summary.title': 'AI 洞察',
    'summary.loading': '正在提取此视频的关键信息，请稍候。',
    'summary.download': '下载字幕',
    'summary.download.srt': '字幕文件 (SRT)',
    'summary.download.txt': '文本（含时间戳）',
    'summary.download.txtNoTs': '文本（仅内容）',
    'article.title': '文章',
    'article.description': '内容按主题分组，每个部分都可以跳转到对应时间点。',
    'article.empty': '字幕准备好后将生成文章视图。',
    'article.expandAll': '全部展开',
    'article.collapseAll': '全部折叠',
    'common.copy': '复制',
    'common.export': '导出',
    'article.now': '当前',
    'timeline.title': '时间线',
    'timeline.description': '重要时刻按时间顺序排列，并高亮当前所在位置。',
    'timeline.empty': '字幕准备好后将显示时间线。',
    'timeline.core': '核心',
    'timeline.important': '重要',
    'timeline.point': '要点',
    'memo.new': '新备忘',
    'memo.placeholder': '写下你此刻的想法...',
    'common.save': '保存',
    'memo.empty': '还没有备忘。',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.cancel': '取消',
    'memo.export': '导出所有备忘 (.txt)',
    'options.title': 'Subtext 设置',
    'options.language': '语言',
    'options.description': '选择用于翻译字幕、AI 摘要、时间线和文章视图的语言。',
    'options.outputLanguage': '输出语言',
    'options.currentSelection': '当前选择：{label}',
    'options.howItWorks': '使用方式',
    'options.rule1': '翻译字幕会遵循此设置。',
    'options.rule2': 'AI 摘要、时间线和文章也会使用相同语言。',
    'options.rule3': '更改设置后，下次面板刷新时会自动生效。',
  },
  'zh-Hant': {
    language: '語言',
    'group.default': '預設',
    'group.global': '全球',
    'group.eastAsia': '東亞',
    'group.indian': '印度語言',
    'group.european': '歐洲語言',
    originalSubtitles: '原始字幕',
    refreshAi: '重新整理 AI',
    refreshing: '重新整理中...',
    aiRetry: '重新產生 AI',
    retry: '重試',
    close: '關閉',
    'tab.script': '腳本',
    'tab.timeline': '時間軸',
    'tab.article': '文章',
    'tab.chat': 'AI聊天',
    playVideo: '播放影片以開始',
    openYoutube: '開啟 YouTube 影片後，AI 會為你分析字幕。',
    'script.empty': '找不到這支影片的字幕。',
    'script.searchPlaceholder': '搜尋字幕...',
    'script.results': '{count} 筆結果',
    'script.segments': '{count} 段',
    'script.autoScroll': '自動捲動',
    'common.on': '開',
    'common.off': '關',
    'summary.title': 'AI 洞察',
    'summary.loading': '正在擷取這支影片的重點內容，請稍候。',
    'summary.download': '下載字幕',
    'summary.download.srt': '字幕檔案 (SRT)',
    'summary.download.txt': '文字（含時間戳）',
    'summary.download.txtNoTs': '文字（僅內容）',
    'article.title': '文章',
    'article.description': '內容會依主題分組，每個段落都可跳轉到對應時間。',
    'article.empty': '字幕準備完成後會產生文章檢視。',
    'article.expandAll': '全部展開',
    'article.collapseAll': '全部收合',
    'common.copy': '複製',
    'common.export': '匯出',
    'article.now': '現在',
    'timeline.title': '時間軸',
    'timeline.description': '重要片段會依時間排序，並標示目前所在位置。',
    'timeline.empty': '字幕準備完成後就會顯示時間軸。',
    'timeline.core': '核心',
    'timeline.important': '重要',
    'timeline.point': '重點',
    'memo.new': '新增備忘',
    'memo.placeholder': '寫下此刻的想法...',
    'common.save': '儲存',
    'memo.empty': '目前沒有備忘。',
    'common.edit': '編輯',
    'common.delete': '刪除',
    'common.cancel': '取消',
    'memo.export': '匯出全部備忘 (.txt)',
    'options.title': 'Subtext 設定',
    'options.language': '語言',
    'options.description': '選擇翻譯字幕、AI 摘要、時間軸與文章檢視要使用的語言。',
    'options.outputLanguage': '輸出語言',
    'options.currentSelection': '目前選擇：{label}',
    'options.howItWorks': '運作方式',
    'options.rule1': '翻譯字幕會依照此設定顯示。',
    'options.rule2': 'AI 摘要、時間軸與文章也會使用相同語言。',
    'options.rule3': '變更設定後，下一次面板重新整理時會自動套用。',
  },
  hi: {
    language: 'भाषा',
    'group.default': 'डिफ़ॉल्ट',
    'group.global': 'वैश्विक',
    'group.eastAsia': 'पूर्व एशिया',
    'group.indian': 'भारतीय भाषाएँ',
    'group.european': 'यूरोपीय भाषाएँ',
    originalSubtitles: 'मूल उपशीर्षक',
    refreshAi: 'AI रीफ़्रेश',
    refreshing: 'रीफ़्रेश हो रहा है...',
    aiRetry: 'AI फिर से बनाएं',
    retry: 'फिर से कोशिश करें',
    close: 'बंद करें',
    'tab.script': 'स्क्रिप्ट',
    'tab.timeline': 'टाइमलाइन',
    'tab.article': 'लेख',
    'tab.chat': 'AI चैट',
    playVideo: 'शुरू करने के लिए वीडियो चलाएँ',
    openYoutube: 'YouTube वीडियो खोलें, AI आपके लिए उपशीर्षकों का विश्लेषण करेगा।',
    'script.empty': 'इस वीडियो के लिए उपशीर्षक नहीं मिले।',
    'script.searchPlaceholder': 'प्रतिलेख खोजें...',
    'script.results': '{count} परिणाम',
    'script.segments': '{count} खंड',
    'script.autoScroll': 'ऑटो-स्क्रोल',
    'common.on': 'चालू',
    'common.off': 'बंद',
    'summary.title': 'AI इनसाइट्स',
    'summary.loading': 'इस वीडियो से मुख्य बिंदु निकाले जा रहे हैं। कृपया प्रतीक्षा करें।',
    'summary.download': 'उपशीर्षक डाउनलोड करें',
    'summary.download.srt': 'उपशीर्षक फ़ाइल (SRT)',
    'summary.download.txt': 'पाठ (टाइमस्टैम्प सहित)',
    'summary.download.txtNoTs': 'पाठ (केवल सामग्री)',
    'article.title': 'लेख',
    'article.description': 'सामग्री विषय के अनुसार समूहित है, और हर खंड अपने समय पर जा सकता है।',
    'article.empty': 'उपशीर्षक तैयार होने पर लेख दृश्य बनाया जाएगा।',
    'article.expandAll': 'सब फैलाएँ',
    'article.collapseAll': 'सब समेटें',
    'common.copy': 'कॉपी',
    'common.export': 'निर्यात',
    'article.now': 'अभी',
    'timeline.title': 'टाइमलाइन',
    'timeline.description': 'महत्वपूर्ण क्षण समय क्रम में व्यवस्थित हैं और वर्तमान बिंदु हाइलाइट किया गया है।',
    'timeline.empty': 'उपशीर्षक तैयार होने पर टाइमलाइन दिखेगी।',
    'timeline.core': 'मुख्य',
    'timeline.important': 'महत्वपूर्ण',
    'timeline.point': 'बिंदु',
    'memo.new': 'नया मेमो',
    'memo.placeholder': 'इस पल अपने विचार लिखें...',
    'common.save': 'सहेजें',
    'memo.empty': 'अभी तक कोई मेमो नहीं है।',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएँ',
    'common.cancel': 'रद्द करें',
    'memo.export': 'सभी मेमो निर्यात करें (.txt)',
    'options.title': 'Subtext सेटिंग्स',
    'options.language': 'भाषा',
    'options.description': 'अनुवादित उपशीर्षक, AI सारांश, टाइमलाइन और लेख दृश्य के लिए भाषा चुनें।',
    'options.outputLanguage': 'आउटपुट भाषा',
    'options.currentSelection': 'वर्तमान चयन: {label}',
    'options.howItWorks': 'यह कैसे काम करता है',
    'options.rule1': 'अनुवादित उपशीर्षक इस सेटिंग का पालन करते हैं।',
    'options.rule2': 'AI सारांश, टाइमलाइन और लेख भी इसी भाषा का उपयोग करते हैं।',
    'options.rule3': 'सेटिंग बदलने पर अगली पैनल रीफ़्रेश पर यह अपने आप लागू हो जाएगी।',
  },
  es: {
    language: 'Idioma',
    'group.default': 'Predeterminado',
    'group.global': 'Global',
    'group.eastAsia': 'Asia oriental',
    'group.indian': 'Idiomas de la India',
    'group.european': 'Idiomas europeos',
    originalSubtitles: 'Subtítulos originales',
    refreshAi: 'Actualizar IA',
    refreshing: 'Actualizando...',
    aiRetry: 'Reintentar IA',
    retry: 'Reintentar',
    close: 'Cerrar',
    'tab.script': 'Guion',
    'tab.timeline': 'Cronología',
    'tab.article': 'Artículo',
    'tab.chat': 'Chat IA',
    playVideo: 'Reproduce un video para empezar',
    openYoutube: 'Abre un video de YouTube y la IA analizará los subtítulos por ti.',
    'script.empty': 'No se encontraron subtítulos para este video.',
    'script.searchPlaceholder': 'Buscar transcripción...',
    'script.results': '{count} resultados',
    'script.segments': '{count} segmentos',
    'script.autoScroll': 'Desplazamiento automático',
    'common.on': 'ACT.',
    'common.off': 'DES.',
    'summary.title': 'Insights de IA',
    'summary.loading': 'Extrayendo ideas clave de este video. Espera un momento.',
    'summary.download': 'Descargar subtítulos',
    'summary.download.srt': 'Archivo de subtítulos (SRT)',
    'summary.download.txt': 'Texto (con marcas de tiempo)',
    'summary.download.txtNoTs': 'Texto (solo contenido)',
    'article.title': 'Artículo',
    'article.description': 'El contenido se agrupa por tema y cada sección puede saltar a su marca de tiempo.',
    'article.empty': 'La vista de artículo se generará cuando los subtítulos estén listos.',
    'article.expandAll': 'Expandir todo',
    'article.collapseAll': 'Contraer todo',
    'common.copy': 'Copiar',
    'common.export': 'Exportar',
    'article.now': 'Ahora',
    'timeline.title': 'Cronología',
    'timeline.description': 'Los momentos importantes se organizan cronológicamente y el punto actual se resalta.',
    'timeline.empty': 'La cronología aparecerá cuando los subtítulos estén listos.',
    'timeline.core': 'Clave',
    'timeline.important': 'Importante',
    'timeline.point': 'Punto',
    'memo.new': 'Nueva nota',
    'memo.placeholder': 'Escribe tus ideas en este momento...',
    'common.save': 'Guardar',
    'memo.empty': 'Todavía no hay notas.',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.cancel': 'Cancelar',
    'memo.export': 'Exportar todas las notas (.txt)',
    'options.title': 'Configuración de Subtext',
    'options.language': 'Idioma',
    'options.description': 'Elige el idioma para subtítulos traducidos, resúmenes de IA, cronología y vista de artículo.',
    'options.outputLanguage': 'Idioma de salida',
    'options.currentSelection': 'Selección actual: {label}',
    'options.howItWorks': 'Cómo funciona',
    'options.rule1': 'Los subtítulos traducidos siguen esta configuración.',
    'options.rule2': 'El resumen, la cronología y el artículo de IA usan el mismo idioma.',
    'options.rule3': 'El cambio se aplica automáticamente la próxima vez que se actualice el panel.',
  },
  fr: {
    language: 'Langue',
    'group.default': 'Par défaut',
    'group.global': 'Global',
    'group.eastAsia': 'Asie de l’Est',
    'group.indian': 'Langues indiennes',
    'group.european': 'Langues européennes',
    originalSubtitles: 'Sous-titres d’origine',
    refreshAi: 'Actualiser l’IA',
    refreshing: 'Actualisation...',
    aiRetry: 'Relancer l’IA',
    retry: 'Réessayer',
    close: 'Fermer',
    'tab.script': 'Script',
    'tab.timeline': 'Chronologie',
    'tab.article': 'Article',
    'tab.chat': 'Chat IA',
    playVideo: 'Lancez une vidéo pour commencer',
    openYoutube: 'Ouvrez une vidéo YouTube et l’IA analysera les sous-titres pour vous.',
  },
  de: {
    language: 'Sprache',
    refreshAi: 'KI aktualisieren',
    refreshing: 'Wird aktualisiert...',
    aiRetry: 'KI erneut ausführen',
    retry: 'Erneut versuchen',
    close: 'Schließen',
    'tab.script': 'Skript',
    'tab.timeline': 'Zeitachse',
    'tab.article': 'Artikel',
    'tab.chat': 'KI-Chat',
    playVideo: 'Starte ein Video, um loszulegen',
    openYoutube: 'Öffne ein YouTube-Video, dann analysiert die KI die Untertitel für dich.',
  },
  it: {
    language: 'Lingua',
    refreshAi: 'Aggiorna IA',
    refreshing: 'Aggiornamento...',
    aiRetry: 'Riprova IA',
    retry: 'Riprova',
    close: 'Chiudi',
    'tab.script': 'Script',
    'tab.timeline': 'Timeline',
    'tab.article': 'Articolo',
    'tab.chat': 'Chat IA',
    playVideo: 'Riproduci un video per iniziare',
    openYoutube: 'Apri un video di YouTube e l’IA analizzerà i sottotitoli per te.',
  },
  pt: {
    language: 'Idioma',
    refreshAi: 'Atualizar IA',
    refreshing: 'Atualizando...',
    aiRetry: 'Tentar IA novamente',
    retry: 'Tentar novamente',
    close: 'Fechar',
    'tab.script': 'Roteiro',
    'tab.timeline': 'Linha do tempo',
    'tab.article': 'Artigo',
    'tab.chat': 'Chat IA',
    playVideo: 'Reproduza um vídeo para começar',
    openYoutube: 'Abra um vídeo do YouTube e a IA analisará as legendas para você.',
  },
  nl: {
    language: 'Taal',
    refreshAi: 'AI verversen',
    refreshing: 'Bezig met verversen...',
    aiRetry: 'AI opnieuw',
    retry: 'Opnieuw proberen',
    close: 'Sluiten',
    'tab.script': 'Script',
    'tab.timeline': 'Tijdlijn',
    'tab.article': 'Artikel',
    'tab.chat': 'AI Chat',
  },
  pl: {
    language: 'Język',
    refreshAi: 'Odśwież AI',
    refreshing: 'Odświeżanie...',
    aiRetry: 'Ponów AI',
    retry: 'Spróbuj ponownie',
    close: 'Zamknij',
    'tab.script': 'Skrypt',
    'tab.timeline': 'Oś czasu',
    'tab.article': 'Artykuł',
    'tab.chat': 'Czat AI',
  },
  sv: { language: 'Språk', refreshAi: 'Uppdatera AI', refreshing: 'Uppdaterar...', aiRetry: 'Kör AI igen', retry: 'Försök igen', close: 'Stäng', 'tab.script': 'Skript', 'tab.timeline': 'Tidslinje', 'tab.article': 'Artikel', 'tab.chat': 'AI Chatt' },
  da: { language: 'Sprog', refreshAi: 'Opdater AI', refreshing: 'Opdaterer...', aiRetry: 'Prøv AI igen', retry: 'Prøv igen', close: 'Luk', 'tab.script': 'Script', 'tab.timeline': 'Tidslinje', 'tab.article': 'Artikel', 'tab.chat': 'AI Chat' },
  no: { language: 'Språk', refreshAi: 'Oppdater AI', refreshing: 'Oppdaterer...', aiRetry: 'Prøv AI på nytt', retry: 'Prøv igjen', close: 'Lukk', 'tab.script': 'Skript', 'tab.timeline': 'Tidslinje', 'tab.article': 'Artikkel', 'tab.chat': 'AI Chat' },
  fi: { language: 'Kieli', refreshAi: 'Päivitä AI', refreshing: 'Päivitetään...', aiRetry: 'Yritä AI uudelleen', retry: 'Yritä uudelleen', close: 'Sulje', 'tab.script': 'Skripti', 'tab.timeline': 'Aikajana', 'tab.article': 'Artikkeli', 'tab.chat': 'Tekoälychatti' },
  cs: { language: 'Jazyk', refreshAi: 'Obnovit AI', refreshing: 'Obnovuje se...', aiRetry: 'Zkusit AI znovu', retry: 'Zkusit znovu', close: 'Zavřít', 'tab.script': 'Přepis', 'tab.timeline': 'Časová osa', 'tab.article': 'Článek', 'tab.chat': 'AI Chat' },
  ro: { language: 'Limbă', refreshAi: 'Reîmprospătează AI', refreshing: 'Se reîmprospătează...', aiRetry: 'Reîncearcă AI', retry: 'Încearcă din nou', close: 'Închide', 'tab.script': 'Transcriere', 'tab.timeline': 'Cronologie', 'tab.article': 'Articol', 'tab.chat': 'Chat AI' },
  hu: { language: 'Nyelv', refreshAi: 'AI frissítése', refreshing: 'Frissítés...', aiRetry: 'AI újra', retry: 'Újrapróbálás', close: 'Bezárás', 'tab.script': 'Szkript', 'tab.timeline': 'Idővonal', 'tab.article': 'Cikk', 'tab.chat': 'AI Chat' },
  el: { language: 'Γλώσσα', refreshAi: 'Ανανέωση AI', refreshing: 'Ανανέωση...', aiRetry: 'Επανάληψη AI', retry: 'Δοκιμή ξανά', close: 'Κλείσιμο', 'tab.script': 'Κείμενο', 'tab.timeline': 'Χρονολόγιο', 'tab.article': 'Άρθρο', 'tab.chat': 'AI Συνομιλία' },
  uk: { language: 'Мова', refreshAi: 'Оновити AI', refreshing: 'Оновлення...', aiRetry: 'Повторити AI', retry: 'Спробувати ще раз', close: 'Закрити', 'tab.script': 'Скрипт', 'tab.timeline': 'Хронологія', 'tab.article': 'Стаття', 'tab.chat': 'AI Чат' },
  tr: { language: 'Dil', refreshAi: 'Yapay zekâyı yenile', refreshing: 'Yenileniyor...', aiRetry: 'Yapay zekâyı yeniden dene', retry: 'Tekrar dene', close: 'Kapat', 'tab.script': 'Metin', 'tab.timeline': 'Zaman çizelgesi', 'tab.article': 'Makale', 'tab.chat': 'AI Sohbet' },
};

export interface UiText {
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
  languageLabel: (option: OutputLanguageOption) => string;
  groupLabel: (group: string) => string;
}

const UiTextContext = createContext<UiText>(createUiText('en'));

export function UiTextProvider({
  language,
  children,
}: {
  language: OutputLanguageCode;
  children: ReactNode;
}) {
  const value = useMemo(() => createUiText(language), [language]);
  return <UiTextContext.Provider value={value}>{children}</UiTextContext.Provider>;
}

export function useUiText() {
  return useContext(UiTextContext);
}

export function createUiText(language: OutputLanguageCode): UiText {
  const locale = resolveUiLocale(language);
  const dict = {
    ...EN_TRANSLATIONS,
    ...(LOCALE_OVERRIDES[locale] ?? {}),
  };

  return {
    t: (key, vars) => interpolate(dict[key], vars),
    languageLabel: (option) => option.code === 'auto' ? dict.originalSubtitles : option.label,
    groupLabel: (group) => {
      if (group === 'Default') return dict['group.default'];
      if (group === 'Global') return dict['group.global'];
      if (group === 'East Asia') return dict['group.eastAsia'];
      if (group === 'Indian languages') return dict['group.indian'];
      if (group === 'European languages') return dict['group.european'];
      return group;
    },
  };
}

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) {
    return template;
  }

  return Object.entries(vars).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

function resolveUiLocale(language: OutputLanguageCode): OutputLanguageCode {
  if (language !== 'auto') {
    return language;
  }

  if (typeof navigator === 'undefined') {
    return 'en';
  }

  const normalized = navigator.language.toLowerCase();
  if (normalized.startsWith('ko')) return 'ko';
  if (normalized.startsWith('ja')) return 'ja';
  if (normalized.startsWith('zh-hant') || normalized.endsWith('-tw') || normalized.endsWith('-hk')) return 'zh-Hant';
  if (normalized.startsWith('zh')) return 'zh-Hans';
  if (normalized.startsWith('hi')) return 'hi';
  if (normalized.startsWith('es')) return 'es';
  if (normalized.startsWith('fr')) return 'fr';
  if (normalized.startsWith('de')) return 'de';
  if (normalized.startsWith('it')) return 'it';
  if (normalized.startsWith('pt')) return 'pt';
  if (normalized.startsWith('nl')) return 'nl';
  if (normalized.startsWith('pl')) return 'pl';
  if (normalized.startsWith('sv')) return 'sv';
  if (normalized.startsWith('da')) return 'da';
  if (normalized.startsWith('no')) return 'no';
  if (normalized.startsWith('fi')) return 'fi';
  if (normalized.startsWith('cs')) return 'cs';
  if (normalized.startsWith('ro')) return 'ro';
  if (normalized.startsWith('hu')) return 'hu';
  if (normalized.startsWith('el')) return 'el';
  if (normalized.startsWith('uk')) return 'uk';
  if (normalized.startsWith('tr')) return 'tr';
  return 'en';
}
