/**
 * MAIN world 스크립트 — YouTube 페이지의 JS 컨텍스트에서 실행
 */
export default defineUnlistedScript({
  main() {
    type AnyObj = Record<string, unknown>;
    type TranscriptSegment = { text: string; offset: number; duration: number; lang: string };
    let watchPageHtmlCache: string | null = null;

    window.addEventListener('message', async (event) => {
      if (event.source !== window) return;
      if (event.data?.type === 'SUBTEXT_LIST_TRACKS') {
        const { requestId } = event.data as { requestId?: string };
        if (!requestId) {
          return;
        }

        try {
          const tracks = await listAvailableSubtitleTracks();
          window.postMessage({ type: 'SUBTEXT_TRACKS_RESULT', requestId, tracks }, '*');
        } catch (e: unknown) {
          window.postMessage({
            type: 'SUBTEXT_TRACKS_RESULT',
            requestId,
            error: e instanceof Error ? e.message : 'Subtitle track extraction failed.',
          }, '*');
        }
        return;
      }

      if (event.data?.type === 'SUBTEXT_CLEAR_TRANSCRIPT_CACHE') {
        const { requestId } = event.data as { requestId?: string };
        if (!requestId) {
          return;
        }
        watchPageHtmlCache = null;
        window.postMessage({
          type: 'SUBTEXT_CLEAR_TRANSCRIPT_CACHE_RESULT',
          requestId,
          cleared: true,
        }, '*');
        return;
      }

      if (event.data?.type === 'SUBTEXT_FETCH_TRACK') {
        const { requestId, track } = event.data as {
          requestId?: string;
          track?: {
            fetchUrl?: string;
            languageCode?: string;
            isAutoGenerated?: boolean;
            label?: string;
            vssId?: string;
            playerTrackData?: AnyObj;
          };
        };
        if (!requestId || !track?.fetchUrl) {
          window.postMessage({ type: 'SUBTEXT_TRACK_RESULT', requestId, error: 'Invalid track request.' }, '*');
          return;
        }

        try {
          const activatedSegments = await activateRequestedTrackAndExtract({
            languageCode: typeof track.languageCode === 'string' ? track.languageCode : '',
            isAutoGenerated: Boolean(track.isAutoGenerated),
            label: typeof track.label === 'string' ? track.label : '',
            vssId: typeof track.vssId === 'string' ? track.vssId : '',
            playerTrackData: isObject(track.playerTrackData) ? track.playerTrackData : null,
          });
          if (activatedSegments.length > 0) {
            window.postMessage({ type: 'SUBTEXT_TRACK_RESULT', requestId, segments: activatedSegments }, '*');
            return;
          }

          const segments = await fetchTrackByUrl(
            track.fetchUrl,
            typeof track.languageCode === 'string' ? track.languageCode : '',
          );
          window.postMessage({ type: 'SUBTEXT_TRACK_RESULT', requestId, segments }, '*');
        } catch (e: unknown) {
          window.postMessage({
            type: 'SUBTEXT_TRACK_RESULT',
            requestId,
            error: e instanceof Error ? e.message : 'Subtitle track fetch failed.',
          }, '*');
        }
        return;
      }

      if (event.data?.type === 'SUBTEXT_TRANSLATE_VIA_YOUTUBE') {
        const { requestId, targetLanguage, videoId: vid } = event.data as { requestId?: string; targetLanguage?: string; videoId?: string };
        if (!requestId || !targetLanguage) {
          window.postMessage({ type: 'SUBTEXT_TRANSLATE_RESULT', requestId, error: 'Invalid request.' }, '*');
          return;
        }

        try {
          const segments = await fetchTranslatedCaptions(targetLanguage, vid);
          window.postMessage({ type: 'SUBTEXT_TRANSLATE_RESULT', requestId, segments }, '*');
        } catch (e: unknown) {
          window.postMessage({
            type: 'SUBTEXT_TRANSLATE_RESULT',
            requestId,
            error: e instanceof Error ? e.message : 'YouTube translation failed.',
          }, '*');
        }
        return;
      }

      if (event.data?.type !== 'SUBTEXT_FETCH_TRANSCRIPT') return;

      const { videoId, requestId } = event.data as { videoId?: string; requestId?: string };
      if (!videoId || !requestId) {
        window.postMessage({ type: 'SUBTEXT_TRANSCRIPT_RESULT', requestId, error: 'Invalid request parameters.' }, '*');
        return;
      }

      try {
        const segments = await extractTranscript(videoId);
        window.postMessage({ type: 'SUBTEXT_TRANSCRIPT_RESULT', requestId, segments }, '*');
      } catch (e: unknown) {
        window.postMessage({
          type: 'SUBTEXT_TRANSCRIPT_RESULT',
          requestId,
          error: e instanceof Error ? e.message : 'Subtitle extraction failed.',
        }, '*');
      }
    });

    window.postMessage({ type: 'SUBTEXT_READY' }, '*');

    // ─── 자막 추출 ─────────────────────────────────────────────

    async function extractTranscript(videoId: string): Promise<TranscriptSegment[]> {
      const retryDelays = [0];
      for (const d of retryDelays) {
        if (d > 0) await sleep(d);
        const segments = await tryAllStrategies(videoId);
        if (segments.length > 0) return segments;
      }
      throw new Error('Could not retrieve subtitle data.');
    }

    async function fetchTranslatedCaptions(targetLanguage: string, videoId?: string): Promise<TranscriptSegment[]> {
      const langCode = normalizeYoutubeTranslationLanguage(targetLanguage);

      // 전략 1: 플레이어 캡션 모듈에서 번역 트랙 활성화 후 TextTrack 추출
      const playerSegments = await fetchTranslatedViaPlayerTrack(langCode);
      if (playerSegments.length > 0) {
        return playerSegments;
      }

      // 전략 2: 캡션 트랙 URL(baseUrl)에 tlang 파라미터를 붙여 직접 요청
      const segments = await fetchTranslatedViaTlang(targetLanguage, videoId);
      if (segments.length > 0) {
        return segments;
      }

      throw new Error('Could not load translated captions.');
    }

    async function fetchTranslatedViaPlayerTrack(targetLanguage: string): Promise<TranscriptSegment[]> {
      const player = getPlayer();
      const video = document.querySelector('video.html5-main-video') as HTMLVideoElement | null;
      if (!player?.getOption || !player?.setOption || !video) {
        return [];
      }

      const previousTrack = player.getOption('captions', 'track') as AnyObj | undefined;
      try {
        player.loadModule?.('captions');
        await sleep(300);

        const tracklist = player.getOption('captions', 'tracklist') as AnyObj[] | undefined;
        if (!Array.isArray(tracklist) || tracklist.length === 0) {
          return [];
        }

        const globalTranslationLanguages = getGlobalTranslationLanguages(player, tracklist);
        const sortedTracks = rankTracksForTranslation(tracklist);
        let found: TranscriptSegment[] = [];

        for (const sourceTrack of sortedTracks) {
          const sourceLanguageCode = readTrackLanguageCode(sourceTrack);
          if (normalizeLanguageCodeForCompare(sourceLanguageCode) === normalizeLanguageCodeForCompare(targetLanguage)) {
            continue;
          }

          const perTrackLanguages = getTrackTranslationLanguages(sourceTrack);
          const translationLanguage = findBestTranslationLanguage(
            targetLanguage,
            perTrackLanguages.length > 0 ? perTrackLanguages : globalTranslationLanguages,
          );
          if (!translationLanguage) {
            continue;
          }

          const translatedTrack = buildTranslatedPlayerTrack(sourceTrack, translationLanguage, targetLanguage);

          for (let i = 0; i < video.textTracks.length; i += 1) {
            try {
              video.textTracks[i].mode = 'disabled';
            } catch {
              // ignore
            }
          }

          try {
            player.setOption('captions', 'track', translatedTrack);
          } catch {
            continue;
          }
          await nudgeVideoForCaptionLoad(video);

          for (let attempt = 0; attempt < 40; attempt += 1) {
            await sleep(200);
            for (let i = 0; i < video.textTracks.length; i += 1) {
              try {
                if (video.textTracks[i].mode === 'disabled') {
                  video.textTracks[i].mode = 'hidden';
                }
              } catch {
                // ignore
              }
            }

            const translatedSegments = getSegmentsFromActiveTextTracks(video);
            if (translatedSegments.length > 0) {
              found = translatedSegments.map((segment) => ({ ...segment, lang: targetLanguage }));
              break;
            }

            if (attempt > 0 && attempt % 10 === 0) {
              try {
                player.setOption('captions', 'track', translatedTrack);
              } catch {
                // ignore
              }
              await nudgeVideoForCaptionLoad(video);
            }
          }

          if (found.length > 0) break;
        }
        return found;
      } catch (error) {
      } finally {
        try {
          if (previousTrack && isObject(previousTrack)) {
            player.setOption('captions', 'track', previousTrack);
          } else {
            player.setOption('captions', 'track', {});
          }
        } catch {
          // ignore
        }
      }

      return [];
    }

    async function fetchTranslatedViaTlang(targetLanguage: string, videoId?: string): Promise<TranscriptSegment[]> {
      const pageTracks = getCaptionTracksFromPageData() ?? [];
      const htmlTracks = await getCaptionTracksFromWatchHtml() ?? [];
      const apiTracks = videoId ? (await getCaptionTracksFromPlayerApi(videoId) ?? []) : [];
      const mergedTracks = mergeCaptionTracks(
        mergeCaptionTracks(apiTracks, htmlTracks),
        pageTracks,
      );

      if (mergedTracks.length === 0) {
        return [];
      }

      const sorted = rankTracksForTranslation(mergedTracks);

      const cleanFetch = getCleanFetch();
      const langCode = normalizeYoutubeTranslationLanguage(targetLanguage);

      for (const track of sorted) {
        const baseUrl = track.baseUrl as string | undefined;
        if (!baseUrl) continue;

        const sourceLang = (track.languageCode as string) || '';
        const trackKind = (track.kind as string) || '';
        const trackVssId = (track.vssId as string) || '';

        try {
          for (const candidateUrl of makeTranslatedCaptionUrlCandidates(baseUrl, {
            sourceLang,
            trackKind,
            trackVssId,
            targetLang: langCode,
          })) {
            const result = await tryFetchTranslation(candidateUrl, langCode, cleanFetch);
            if (result.segments.length > 0) return result.segments;
            if (result.shouldAbort) {
              return [];
            }
          }
        } catch (e) {
        }
      }

      return [];
    }

    async function tryFetchTranslation(
      url: string,
      langCode: string,
      cleanFetch: typeof fetch,
    ): Promise<{ segments: TranscriptSegment[]; shouldAbort: boolean }> {

      try {
        const resp = await cleanFetch(url, { credentials: 'include' });
        if (!resp.ok) {
          return {
            segments: [],
            shouldAbort: resp.status === 429,
          };
        }

        const text = await resp.text();
        if (!text.trim()) {
          return { segments: [], shouldAbort: false };
        }

        // JSON
        try {
          const json = JSON.parse(text) as AnyObj;
          const parsed = parseJson3Captions(json, langCode);
          if (parsed.length > 0) {
            return {
              segments: parsed.map((seg) => ({ ...seg, lang: langCode })),
              shouldAbort: false,
            };
          }
        } catch { /* not JSON */ }

        // XML
        const xmlParsed = parseXmlCaptions(text, langCode);
        if (xmlParsed.length > 0) {
          return {
            segments: xmlParsed.map((seg) => ({ ...seg, lang: langCode })),
            shouldAbort: false,
          };
        }

      } catch (e) {
      }
      return { segments: [], shouldAbort: false };
    }

    async function listAvailableSubtitleTracks(): Promise<Array<{
      id: string;
      label: string;
      languageCode: string;
      isAutoGenerated: boolean;
      fetchUrl: string;
      vssId?: string;
      playerTrackData?: AnyObj;
      source: 'youtube';
    }>> {
      const playerTracklist = getPlayerTracklist();
      const pageTracks = getCaptionTracksFromPageData() ?? [];
      const htmlTracks = await getCaptionTracksFromWatchHtml() ?? [];
      const merged = mergeCaptionTracks(pageTracks, htmlTracks);

      return dedupeTrackOptions(
        merged
          .map((track) => mapCaptionTrackOption(track))
          .filter((track): track is {
            id: string;
            label: string;
            languageCode: string;
            isAutoGenerated: boolean;
            fetchUrl: string;
            vssId?: string;
            playerTrackData?: AnyObj;
            source: 'youtube';
          } => track !== null)
          .map((track) => ({
            ...track,
            playerTrackData: track.playerTrackData ?? findBestMatchingPlayerTrack(playerTracklist, {
              languageCode: track.languageCode,
              isAutoGenerated: track.isAutoGenerated,
              label: track.label,
              vssId: track.vssId ?? '',
            }),
          }))
          .sort((a, b) => {
          if (a.isAutoGenerated !== b.isAutoGenerated) {
            return Number(a.isAutoGenerated) - Number(b.isAutoGenerated);
          }
          return a.label.localeCompare(b.label);
        }),
      );
    }

    async function activateRequestedTrackAndExtract(track: {
      languageCode: string;
      isAutoGenerated: boolean;
      label: string;
      vssId: string;
      playerTrackData: AnyObj | null;
    }): Promise<TranscriptSegment[]> {
      const player = getPlayer();
      const video = document.querySelector('video.html5-main-video') as HTMLVideoElement | null;
      if (!player?.getOption || !player?.setOption || !video) {
        return [];
      }

      try {
        player.loadModule?.('captions');
        await sleep(300);

        const tracklist = player.getOption('captions', 'tracklist') as AnyObj[] | undefined;
        if (!Array.isArray(tracklist) || tracklist.length === 0) {
          return [];
        }

        const requested = track.playerTrackData ?? findBestMatchingPlayerTrack(tracklist, track);
        if (!requested) {
          return [];
        }

        for (let i = 0; i < video.textTracks.length; i += 1) {
          try {
            video.textTracks[i].mode = 'disabled';
          } catch {
            // ignore
          }
        }

        player.setOption('captions', 'track', requested);
        await nudgeVideoForCaptionLoad(video);

        for (let attempt = 0; attempt < 60; attempt += 1) {
          await sleep(200);
          for (let i = 0; i < video.textTracks.length; i += 1) {
            try {
              if (video.textTracks[i].mode === 'disabled') {
                video.textTracks[i].mode = 'hidden';
              }
            } catch {
              // ignore
            }
          }
          const activeSegments = getSegmentsFromActiveTextTracks(video);
          if (activeSegments.length > 0) {
            return activeSegments.map((segment) => ({
              ...segment,
              lang: track.languageCode || segment.lang,
            }));
          }

          if (attempt % 10 === 0) {
            if (attempt > 0) {
              try {
                player.setOption('captions', 'track', requested);
              } catch {
                // ignore
              }
              await nudgeVideoForCaptionLoad(video);
            }
          }
        }
      } catch (error) {
      } finally {
        try {
          player.setOption?.('captions', 'track', {});
        } catch {
          // ignore
        }
      }

      return [];
    }

    async function nudgeVideoForCaptionLoad(video: HTMLVideoElement): Promise<void> {
      try {
        const originalTime = video.currentTime;
        const duration = Number.isFinite(video.duration) ? video.duration : 0;
        const nudgedTime = duration > 0
          ? Math.min(originalTime + 0.05, Math.max(0, duration - 0.05))
          : originalTime + 0.05;

        if (Math.abs(nudgedTime - originalTime) > 0.0001) {
          video.currentTime = nudgedTime;
          await sleep(120);
          video.currentTime = originalTime;
          await sleep(120);
          return;
        }
      } catch {
        // ignore seek-based nudge failure
      }

      if (video.paused) {
        const previousMuted = video.muted;
        try {
          video.muted = true;
          await video.play();
          await sleep(200);
          video.pause();
        } catch {
          // ignore play-based nudge failure
        } finally {
          video.muted = previousMuted;
        }
      }
    }

    async function fetchTrackByUrl(fetchUrl: string, lang: string): Promise<TranscriptSegment[]> {
      const cleanFetch = getCleanFetch();

      for (const url of makeCaptionUrlCandidates(fetchUrl)) {
        const captionResp = await fetchCaptionUrl(url, cleanFetch);
        if (!captionResp || !captionResp.ok) {
          continue;
        }

        const text = await captionResp.text();
        if (!text.trim()) {
          continue;
        }

        try {
          const json = JSON.parse(text) as AnyObj;
          const parsed = parseJson3Captions(json, lang);
          if (parsed.length > 0) {
            return parsed;
          }
        } catch {
          // ignore
        }

        const parsed = parseXmlCaptions(text, lang);
        if (parsed.length > 0) {
          return parsed;
        }

        const parsedVtt = parseVttCaptions(text, lang);
        if (parsedVtt.length > 0) {
          return parsedVtt;
        }
      }

      throw new Error('Could not retrieve subtitle data.');
    }

    async function tryAllStrategies(videoId: string): Promise<TranscriptSegment[]> {
      void videoId;
      // 전략 4만 사용: 트랜스크립트 패널 열기 + DOM 스크래핑
      const domSegments = await openTranscriptPanelAndScrape();
      if (domSegments.length > 0) {
        // DOM 스크래핑은 lang이 빈 문자열이므로, 캡션 트랙 데이터에서 언어 추론
        if (!domSegments[0].lang) {
          const detectedLang = detectTranscriptLanguage();
          if (detectedLang) {
            for (const seg of domSegments) {
              seg.lang = detectedLang;
            }
          }
        }
        return domSegments;
      }

      return [];
    }

    function detectTranscriptLanguage(): string {
      // 1. 트랜스크립트 패널의 언어 선택 드롭다운에서 현재 선택된 언어 확인
      const panel = getTranscriptPanelElement();
      if (panel) {
        const dropdown = panel.querySelector<HTMLElement>('tp-yt-paper-dropdown-menu, ytd-dropdown-renderer');
        const selectedText = dropdown?.querySelector<HTMLElement>('tp-yt-paper-item[aria-selected="true"], yt-formatted-string')?.textContent?.trim();
        if (selectedText) {
          const langFromLabel = inferLangCodeFromLabel(selectedText);
          if (langFromLabel) return langFromLabel;
        }
      }

      // 2. 캡션 트랙 데이터에서 기본 트랙의 언어 코드 가져오기
      const tracks = getCaptionTracksFromPageData();
      if (Array.isArray(tracks) && tracks.length > 0) {
        // 수동 자막 우선, 없으면 첫 번째 트랙
        const manual = tracks.find((t) => (t as AnyObj).kind !== 'asr');
        const track = manual ?? tracks[0];
        const langCode = (track as AnyObj).languageCode;
        if (typeof langCode === 'string' && langCode) return langCode;
      }

      return '';
    }

    function inferLangCodeFromLabel(label: string): string {
      const lower = label.toLowerCase();
      const mapping: Array<[string[], string]> = [
        [['english'], 'en'],
        [['korean', '한국어'], 'ko'],
        [['japanese', '日本語'], 'ja'],
        [['chinese (simplified)', '中文(简体)'], 'zh-Hans'],
        [['chinese (traditional)', '中文(繁體)'], 'zh-Hant'],
        [['spanish', 'español'], 'es'],
        [['french', 'français'], 'fr'],
        [['german', 'deutsch'], 'de'],
        [['italian', 'italiano'], 'it'],
        [['portuguese', 'português'], 'pt'],
        [['hindi', 'हिन्दी'], 'hi'],
        [['turkish', 'türkçe'], 'tr'],
      ];
      for (const [keywords, code] of mapping) {
        if (keywords.some((k) => lower.includes(k))) return code;
      }
      return '';
    }

    // ─── 전략 1: 플레이어 캡션 활성화 후 TextTrack cue 추출 ──────

    async function activatePlayerCaptionsAndExtract(): Promise<TranscriptSegment[]> {
      const player = getPlayer();
      if (!player?.getOption || !player?.setOption) return [];

      const video = document.querySelector('video.html5-main-video') as HTMLVideoElement | null;
      if (!video) return [];

      // 이미 textTrack에 cue가 있는지 확인
      const existing = getSegmentsFromTextTracks(video);
      if (existing.length > 0) return existing;

      try {
        // 캡션 모듈 로드
        player.loadModule?.('captions');
        await sleep(300);

        // tracklist에서 사용 가능한 트랙 가져오기
        const tracklist = player.getOption('captions', 'tracklist') as AnyObj[] | undefined;
        if (!Array.isArray(tracklist) || tracklist.length === 0) {
          return [];
        }


        // 첫 번째 트랙 활성화
        const trackToActivate = tracklist[0];
        player.setOption('captions', 'track', trackToActivate);

        // textTrack이 나타나고 cue가 로드될 때까지 대기
        for (let attempt = 0; attempt < 30; attempt++) {
          await sleep(200);

          const segments = getSegmentsFromTextTracks(video);
          if (segments.length > 0) {
            // 캡션 비활성화 (사용자 화면에서 숨기기)
            try { player.setOption('captions', 'track', {}); } catch { /* ignore */ }
            return segments;
          }
        }

        // 캡션 비활성화
        try { player.setOption('captions', 'track', {}); } catch { /* ignore */ }
      } catch (e) {
      }

      return [];
    }

    function getSegmentsFromTextTracks(video: HTMLVideoElement): TranscriptSegment[] {
      const tracks = video.textTracks;
      for (let i = 0; i < tracks.length; i++) {
        const track = tracks[i];
        // hidden 모드로 변경하여 cue 접근 가능하게
        if (track.mode === 'disabled') {
          track.mode = 'hidden';
        }
        if (track.cues && track.cues.length > 0) {
          return extractCuesFromTrack(track);
        }
      }
      return [];
    }

    function extractCuesFromTrack(track: TextTrack): TranscriptSegment[] {
      if (!track.cues) return [];
      const segments: TranscriptSegment[] = [];
      for (let i = 0; i < track.cues.length; i++) {
        const cue = track.cues[i] as VTTCue;
        const text = (cue.text ?? '').replace(/<[^>]+>/g, '').trim();
        if (!text) continue;
        segments.push({
          text,
          offset: cue.startTime,
          duration: cue.endTime - cue.startTime,
          lang: track.language || '',
        });
      }
      return normalizeSegments(segments);
    }

    function getSegmentsFromActiveTextTracks(video: HTMLVideoElement): TranscriptSegment[] {
      const tracks = video.textTracks;
      for (let index = 0; index < tracks.length; index += 1) {
        const track = tracks[index];
        if (track.mode === 'disabled') {
          continue;
        }
        if (track.cues && track.cues.length > 0) {
          return extractCuesFromTrack(track);
        }
      }

      return getSegmentsFromTextTracks(video);
    }

    // ─── 전략 2: captionTracks URL에서 자막 직접 fetch ──────────

    async function fetchViaCaptionTracksUrl(videoId: string): Promise<TranscriptSegment[]> {
      // 페이지 데이터 + player API(최신) 결과를 병합해 만료된 URL을 회피
      const pageTracks = getCaptionTracksFromPageData() ?? [];
      const htmlTracks = await getCaptionTracksFromWatchHtml();
      const apiTracks = await getCaptionTracksFromPlayerApi(videoId);
      const captionTracks = mergeCaptionTracks(
        mergeCaptionTracks(apiTracks ?? [], htmlTracks ?? []),
        pageTracks,
      );

      if (!Array.isArray(captionTracks) || captionTracks.length === 0) {
        return [];
      }


      const sortedTracks = [...captionTracks].sort((a, b) => {
        const aAsr = a.kind === 'asr' ? 1 : 0;
        const bAsr = b.kind === 'asr' ? 1 : 0;
        return aAsr - bAsr;
      });

      const cleanFetch = getCleanFetch();
      for (const track of sortedTracks) {
        const baseUrl = track.baseUrl as string | undefined;
        if (!baseUrl) continue;

        const lang = (track.languageCode as string) || '';
        const candidates = makeCaptionUrlCandidates(baseUrl);
        for (const url of candidates) {
          const captionResp = await fetchCaptionUrl(url, cleanFetch);
          if (!captionResp || !captionResp.ok) {
            continue;
          }

          const text = await captionResp.text();
          if (!text.trim()) continue;

          // 먼저 JSON 파싱, 실패하면 XML 파싱
          try {
            const json = JSON.parse(text) as AnyObj;
            const parsed = parseJson3Captions(json, lang);
            if (parsed.length > 0) return parsed;
          } catch {
            const parsed = parseXmlCaptions(text, lang);
            if (parsed.length > 0) return parsed;
            const parsedVtt = parseVttCaptions(text, lang);
            if (parsedVtt.length > 0) return parsedVtt;
          }
        }
      }
      return [];
    }

    function getCaptionTracksFromPageData(): AnyObj[] | null {
      // ytInitialPlayerResponse에서 captionTracks 추출
      const w = window as unknown as AnyObj;

      // 방법 1: ytInitialPlayerResponse 글로벌 변수
      if (isObject(w.ytInitialPlayerResponse)) {
        const tracks = extractCaptionTracks(w.ytInitialPlayerResponse as AnyObj);
        if (tracks) return tracks;
      }

      // 방법 2: player.getPlayerResponse() 메서드
      const player = getPlayer() as (PlayerElement & { getPlayerResponse?: () => AnyObj }) | null;
      if (player?.getPlayerResponse) {
        try {
          const resp = player.getPlayerResponse();
          if (isObject(resp)) {
            const tracks = extractCaptionTracks(resp);
            if (tracks) return tracks;
          }
        } catch { /* ignore */ }
      }

      // 방법 3: script 태그에서 ytInitialPlayerResponse 파싱
      try {
        for (const s of Array.from(document.querySelectorAll('script'))) {
          const text = s.textContent ?? '';
          const m = text.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/);
          if (m?.[1]) {
            try {
              const parsed = JSON.parse(m[1]) as AnyObj;
              const tracks = extractCaptionTracks(parsed);
              if (tracks) return tracks;
            } catch { /* */ }
          }
        }
      } catch { /* */ }

      return null;
    }

    function extractCaptionTracks(playerResponse: AnyObj): AnyObj[] | null {
      const captions = playerResponse.captions as AnyObj | undefined;
      if (!isObject(captions)) return null;
      const renderer = captions.playerCaptionsTracklistRenderer as AnyObj | undefined;
      if (!isObject(renderer)) return null;
      const tracks = renderer.captionTracks;
      if (Array.isArray(tracks) && tracks.length > 0) {
        return tracks as AnyObj[];
      }
      return null;
    }

    function mapCaptionTrackOption(track: AnyObj, playerTrackData?: AnyObj): {
      id: string;
      label: string;
      languageCode: string;
      isAutoGenerated: boolean;
      fetchUrl: string;
      vssId?: string;
      playerTrackData?: AnyObj;
      source: 'youtube';
    } | null {
      const fetchUrl = typeof track.baseUrl === 'string' ? track.baseUrl : '';
      if (!fetchUrl) return null;

      const languageCode = typeof track.languageCode === 'string' ? track.languageCode : '';
      const isAutoGenerated = track.kind === 'asr';
      const vssId = typeof track.vssId === 'string' ? track.vssId : '';
      const label = readCaptionTrackText(track.name) || languageCode || 'Unknown';

      return {
        id: `youtube:${languageCode}:${isAutoGenerated ? 'auto' : 'manual'}:${vssId || fetchUrl}`,
        label,
        languageCode,
        isAutoGenerated,
        vssId,
        playerTrackData,
        fetchUrl,
        source: 'youtube',
      };
    }

    function findBestMatchingPlayerTrack(
      tracklist: AnyObj[],
      requested: { languageCode: string; isAutoGenerated: boolean; label: string; vssId: string },
    ): AnyObj | null {
      const normalizedLabel = normalizeTrackLabel(requested.label);
      const normalizedLanguage = requested.languageCode.trim().toLowerCase();
      const requestedKind = requested.isAutoGenerated ? 'asr' : '';

      const scoreTrack = (track: AnyObj) => {
        let score = 0;
        const languageCode = typeof track.languageCode === 'string' ? track.languageCode.trim().toLowerCase() : '';
        const kind = track.kind === 'asr' ? 'asr' : '';
        const vssId = typeof track.vss_id === 'string'
          ? track.vss_id
          : (typeof track.vssId === 'string' ? track.vssId : '');
        const label = normalizeTrackLabel(readCaptionTrackText(track.name));

        if (normalizedLanguage && languageCode === normalizedLanguage) score += 4;
        if (requestedKind === kind) score += 3;
        if (requested.vssId && vssId === requested.vssId) score += 6;
        if (normalizedLabel && label === normalizedLabel) score += 2;
        return score;
      };

      const ranked = tracklist
        .map((track) => ({ track, score: scoreTrack(track) }))
        .filter((entry) => entry.score > 0)
        .sort((a, b) => b.score - a.score);

      return ranked[0]?.track ?? null;
    }

    function readCaptionTrackText(value: unknown): string {
      if (!isObject(value)) return '';
      const simpleText = value.simpleText;
      if (typeof simpleText === 'string') {
        return simpleText.trim();
      }

      const runs = value.runs;
      if (Array.isArray(runs)) {
        return runs
          .map((run) => (isObject(run) && typeof run.text === 'string' ? run.text : ''))
          .join('')
          .trim();
      }

      return '';
    }

    function dedupeTrackOptions(tracks: Array<{
      id: string;
      label: string;
      languageCode: string;
      isAutoGenerated: boolean;
      fetchUrl: string;
      vssId?: string;
      playerTrackData?: AnyObj;
      source: 'youtube';
    }>) {
      const seen = new Set<string>();
      const out: typeof tracks = [];

      for (const track of tracks) {
        const key = [
          track.languageCode.trim().toLowerCase(),
          track.isAutoGenerated ? 'auto' : 'manual',
          normalizeTrackLabel(track.label),
        ].join('|');

        if (seen.has(key)) {
          const existing = out.find((item) => [
            item.languageCode.trim().toLowerCase(),
            item.isAutoGenerated ? 'auto' : 'manual',
            normalizeTrackLabel(item.label),
          ].join('|') === key);
          if (existing && !existing.playerTrackData && track.playerTrackData) {
            existing.playerTrackData = track.playerTrackData;
            existing.vssId = existing.vssId || track.vssId;
            existing.fetchUrl = existing.fetchUrl || track.fetchUrl;
          }
          continue;
        }

        seen.add(key);
        out.push(track);
      }

      return out;
    }

    function normalizeTrackLabel(label: string) {
      return label.trim().replace(/\s+/g, ' ').toLowerCase();
    }

    function getPlayerTracklist(): AnyObj[] {
      try {
        const player = getPlayer();
        const tracklist = player?.getOption?.('captions', 'tracklist') as AnyObj[] | undefined;
        return Array.isArray(tracklist) ? tracklist : [];
      } catch {
        return [];
      }
    }

    function parseJson3Captions(data: AnyObj, lang: string): TranscriptSegment[] {
      const events = data.events as AnyObj[] | undefined;
      if (!Array.isArray(events)) return [];

      const segments: TranscriptSegment[] = [];
      for (const ev of events) {
        const segs = ev.segs as AnyObj[] | undefined;
        if (!Array.isArray(segs)) continue;
        const text = segs.map(s => (s.utf8 as string) || '').join('').trim();
        if (!text || text === '\n') continue;
        const tStartMs = Number(ev.tStartMs);
        const dDurationMs = Number(ev.dDurationMs);
        if (!Number.isFinite(tStartMs)) continue;
        segments.push({
          text,
          offset: tStartMs / 1000,
          duration: Number.isFinite(dDurationMs) ? dDurationMs / 1000 : 0,
          lang,
        });
      }
      return normalizeSegments(segments);
    }

    function parseXmlCaptions(xml: string, lang: string): TranscriptSegment[] {
      const parser = new DOMParser();
      const doc = parser.parseFromString(xml, 'text/xml');
      const textElements = doc.querySelectorAll('text');
      const segments: TranscriptSegment[] = [];

      for (const el of Array.from(textElements)) {
        const text = (el.textContent ?? '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'").replace(/&quot;/g, '"').trim();
        if (!text) continue;
        const start = parseFloat(el.getAttribute('start') ?? '0');
        const dur = parseFloat(el.getAttribute('dur') ?? '0');
        segments.push({ text, offset: start, duration: dur, lang });
      }
      return normalizeSegments(segments);
    }

    function parseVttCaptions(vtt: string, lang: string): TranscriptSegment[] {
      const segments: TranscriptSegment[] = [];
      const blocks = vtt.split(/\n\n+/);

      for (const block of blocks) {
        const lines = block.trim().split('\n');
        const timeLine = lines.find((line) => line.includes('-->'));
        if (!timeLine) continue;

        const [startStr, endStr] = timeLine.split('-->').map((value) => value.trim());
        const start = parseVttTime(startStr);
        const end = parseVttTime(endStr);
        const text = lines
          .slice(lines.indexOf(timeLine) + 1)
          .join(' ')
          .replace(/<[^>]+>/g, '')
          .trim();

        if (!text) continue;
        segments.push({
          text,
          offset: start,
          duration: end > start ? end - start : 0,
          lang,
        });
      }

      return normalizeSegments(segments);
    }

    function parseVttTime(value: string): number {
      const clean = value.split(/\s+/)[0];
      const parts = clean.split(':');
      if (parts.length === 3) {
        return parseFloat(parts[0]) * 3600 + parseFloat(parts[1]) * 60 + parseFloat(parts[2].replace(',', '.'));
      }
      if (parts.length === 2) {
        return parseFloat(parts[0]) * 60 + parseFloat(parts[1].replace(',', '.'));
      }
      return parseFloat(clean.replace(',', '.')) || 0;
    }

    // ─── 전략 3: INNERTUBE get_transcript API ───────────────────

    async function fetchViaGetTranscript(videoId: string): Promise<TranscriptSegment[]> {
      const context = await getInnertubeContext();
      if (!context) {
        return [];
      }

      const params = await getTranscriptParams();
      if (!params) {
        return [];
      }

      const cleanFetch = getCleanFetch();
      const apiKey = getInnertubeApiKey();
      const keyParam = apiKey ? `&key=${apiKey}` : '';
      const client = getInnertubeClientInfo();

      const resp = await cleanFetch(
        `${location.origin}/youtubei/v1/get_transcript?prettyPrint=false${keyParam}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            ...(client.name ? { 'X-Youtube-Client-Name': client.name } : {}),
            ...(client.version ? { 'X-Youtube-Client-Version': client.version } : {}),
          },
          credentials: 'include',
          body: JSON.stringify({
            context: normalizeInnertubeContext(context),
            params,
            externalVideoId: videoId,
          }),
        },
      );

      if (!resp.ok) {
        try {
          const errText = await resp.text();
        } catch { /* ignore */ }
        return [];
      }

      const data = await resp.json() as AnyObj;
      return normalizeSegments(parseGetTranscriptResponse(data));
    }

    // ─── 전략 4: 트랜스크립트 패널 열기 + DOM 스크래핑 ───────────

    async function openTranscriptPanelAndScrape(): Promise<TranscriptSegment[]> {
      const existing = scrapeTranscriptFromDom();
      if (existing.length > 0) return existing;

      const ui = captureUiState();
      let openedByUs = false;
      let hideStyle: HTMLStyleElement | null = null;
      try {
        if (!ui.panelWasOpen) {
          // 패널이 열릴 때 사용자에게 보이지 않도록 CSS로 숨김
          hideStyle = document.createElement('style');
          hideStyle.textContent = `
            /* 패널 자체를 문서 흐름에서 제거 (레이아웃 밀림 방지) + 투명 처리 */
            ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"],
            ytd-engagement-panel-section-list-renderer[visibility="ENGAGEMENT_PANEL_VISIBILITY_EXPANDED"] {
              position: fixed !important;
              top: 0 !important;
              right: 0 !important;
              width: 400px !important;
              height: 100vh !important;
              opacity: 0 !important;
              pointer-events: none !important;
              z-index: -1 !important;
            }
            /* YouTube가 패널 열릴 때 #panels, #secondary 레이아웃을 변경하는 것 방지 */
            ytd-watch-flexy[flexy_] #secondary.ytd-watch-flexy,
            ytd-watch-flexy #secondary.ytd-watch-flexy,
            ytd-watch-flexy #panels.ytd-watch-flexy {
              max-width: none !important;
              transform: none !important;
              margin: 0 !important;
            }
          `;
          document.head.appendChild(hideStyle);

          openedByUs = await tryOpenTranscriptPanel();
          if (!openedByUs) {
            hideStyle.remove();
            hideStyle = null;
            return [];
          }
          // 패널 렌더 대기
          await sleep(500);
        }

        for (let i = 0; i < 12; i++) {
          await sleep(200);
          const segs = scrapeTranscriptFromDom();
          if (segs.length > 0) {
            // 추출 성공 → 숨김 CSS 제거 + 패널 닫기
            if (hideStyle) { hideStyle.remove(); hideStyle = null; }
            if (openedByUs) {
              closeTranscriptPanel();
              openedByUs = false;
            }
            return segs;
          }
        }
        return [];
      } finally {
        if (hideStyle) hideStyle.remove();
        restoreUiState(ui, openedByUs);
      }
    }

    async function tryOpenTranscriptPanel(): Promise<boolean> {
      // livewiki와 동일하게 watch metadata의 transcript CTA를 우선 클릭
      const watchMeta = document.querySelector('ytd-watch-metadata');
      const transcriptCtaSelector = 'button.yt-spec-button-shape-next.yt-spec-button-shape-next--outline.yt-spec-button-shape-next--call-to-action.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--enable-backdrop-filter-experiment';
      const cta = watchMeta?.querySelector<HTMLElement>(transcriptCtaSelector);
      if (cta) {
        cta.click();
        return true;
      }

      const labels = ['transcript', 'show transcript', 'open transcript', '스크립트', '대본'];
      for (let attempt = 0; attempt < 4; attempt++) {
        const clickable = Array.from(document.querySelectorAll<HTMLElement>('button, tp-yt-paper-item, ytd-menu-service-item-renderer'));
        for (const el of clickable) {
          const text = (el.innerText || el.textContent || '').toLowerCase().trim();
          if (!text) continue;
          if (labels.some((k) => text.includes(k))) {
            el.click();
            return true;
          }
        }

        // transcript 메뉴가 안 보이면 "더보기/More actions" 메뉴를 열어본다.
        const moreButtons = Array.from(document.querySelectorAll<HTMLElement>('button[aria-label], yt-icon-button button[aria-label]'));
        let openedMenu = false;
        for (const btn of moreButtons) {
          const label = (btn.getAttribute('aria-label') || '').toLowerCase();
          if (!label) continue;
          if (label.includes('more') || label.includes('action') || label.includes('더보기') || label.includes('추가')) {
            btn.click();
            openedMenu = true;
            break;
          }
        }
        if (openedMenu) await sleep(220);
      }
      return false;
    }

    function closeTranscriptPanel(): void {
      const expandedPanels = Array.from(
        document.querySelectorAll<HTMLElement>(
          'ytd-engagement-panel-section-list-renderer[visibility="ENGAGEMENT_PANEL_VISIBILITY_EXPANDED"]',
        ),
      );
      for (const panel of expandedPanels) {
        panel.setAttribute('visibility', 'ENGAGEMENT_PANEL_VISIBILITY_HIDDEN');
      }

      const closeButtons = Array.from(
        document.querySelectorAll<HTMLElement>(
          'ytd-engagement-panel-title-header-renderer button, ytd-engagement-panel-section-list-renderer button[aria-label], button[aria-label="Close"]',
        ),
      );
      for (const btn of closeButtons) {
        const label = (btn.getAttribute('aria-label') || btn.innerText || '').toLowerCase();
        if (!label) continue;
        if (label.includes('close') || label.includes('닫기')) {
          btn.click();
          return;
        }
      }

      // 마지막 fallback: ESC로 패널 닫기
      document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
      document.dispatchEvent(new KeyboardEvent('keyup', { key: 'Escape', bubbles: true }));
    }

    type UiState = {
      scrollX: number;
      scrollY: number;
      activeElement: HTMLElement | null;
      panelWasOpen: boolean;
    };

    function captureUiState(): UiState {
      const active = document.activeElement instanceof HTMLElement ? document.activeElement : null;
      return {
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        activeElement: active,
        panelWasOpen: isTranscriptPanelOpen(),
      };
    }

    function restoreUiState(state: UiState, openedByUs: boolean): void {
      if (openedByUs) closeTranscriptPanel();
      window.scrollTo(state.scrollX, state.scrollY);
      try {
        state.activeElement?.focus({ preventScroll: true });
      } catch { /* ignore */ }
    }

    function isTranscriptPanelOpen(): boolean {
      const panel = getTranscriptPanelElement();
      if (!panel) return false;
      const visibility = panel.getAttribute('visibility');
      return visibility === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED' || panel.offsetParent !== null;
    }

    function getTranscriptPanelElement(): HTMLElement | null {
      return document.querySelector<HTMLElement>(
        'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"]',
      );
    }


    function scrapeTranscriptFromDom(): TranscriptSegment[] {
      // YouTube의 이미 렌더링된 transcript 패널에서 세그먼트 읽기
      const segmentEls = document.querySelectorAll('ytd-transcript-segment-renderer, div.segment.style-scope.ytd-transcript-segment-renderer');
      if (segmentEls.length === 0) return [];

      const segments: TranscriptSegment[] = [];
      for (const el of Array.from(segmentEls)) {
        const timestampEl = el.querySelector('.segment-timestamp, .cue-group-start-offset, #start-offset');
        const textEl = el.querySelector('.segment-text, #segment-text, yt-formatted-string');
        if (!timestampEl || !textEl) continue;

        const text = (textEl.textContent ?? '').trim();
        if (!text) continue;

        const timeStr = (timestampEl.textContent ?? '').trim();
        const offset = parseTimestamp(timeStr);
        segments.push({ text, offset, duration: 0, lang: '' });
      }
      return normalizeSegments(segments);
    }

    function parseTimestamp(ts: string): number {
      const parts = ts.split(':').map(Number);
      if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
      if (parts.length === 2) return parts[0] * 60 + parts[1];
      return parts[0] || 0;
    }

    // ─── Helpers ─────────────────────────────────────────────────

    type PlayerElement = HTMLElement & {
      getOption?: (module: string, option: string) => unknown;
      setOption?: (module: string, option: string, value: unknown) => void;
      loadModule?: (name: string) => void;
    };

    function getPlayer(): PlayerElement | null {
      return document.getElementById('movie_player') as PlayerElement | null;
    }

    function getCleanFetch(): typeof fetch {
      // 확장 프로그램 등에 의해 가로채기된 fetch를 우회하기 위해 iframe 사용
      try {
        const iframe = document.createElement('iframe');
        iframe.style.display = 'none';
        document.body.appendChild(iframe);
        const f = iframe.contentWindow!.fetch.bind(iframe.contentWindow!);
        // 이후 정리를 위해 iframe 유지 (GC에 의해 정리됨)
        setTimeout(() => iframe.remove(), 30000);
        return f;
      } catch {
        return fetch;
      }
    }

    async function getInnertubeContext(): Promise<AnyObj | null> {
      const w = window as unknown as AnyObj;
      const ytcfg = w.ytcfg as { get?: (key: string) => unknown } | undefined;
      const ctx = ytcfg?.get?.('INNERTUBE_CONTEXT');
      if (isObject(ctx)) return ctx;

      const html = await getWatchPageHtml();
      const cfg = extractYtcfgFromHtml(html);
      if (isObject(cfg?.INNERTUBE_CONTEXT)) return cfg.INNERTUBE_CONTEXT as AnyObj;
      return null;
    }

    function getInnertubeApiKey(): string | null {
      const w = window as unknown as AnyObj;
      const ytcfg = w.ytcfg as { get?: (key: string) => unknown } | undefined;
      const key = ytcfg?.get?.('INNERTUBE_API_KEY');
      if (typeof key === 'string' && key.length > 0) return key;

      const cfg = extractYtcfgFromHtml(watchPageHtmlCache);
      const htmlKey = cfg?.INNERTUBE_API_KEY;
      if (typeof htmlKey === 'string' && htmlKey.length > 0) return htmlKey;
      return null;
    }

    function getInnertubeClientInfo(): { name: string | null; version: string | null } {
      const w = window as unknown as AnyObj;
      const ytcfg = w.ytcfg as { get?: (key: string) => unknown } | undefined;
      const name = ytcfg?.get?.('INNERTUBE_CLIENT_NAME');
      const version = ytcfg?.get?.('INNERTUBE_CLIENT_VERSION');
      if (typeof name === 'string' && typeof version === 'string') {
        return { name, version };
      }
      const cfg = extractYtcfgFromHtml(watchPageHtmlCache);
      const htmlName = cfg?.INNERTUBE_CLIENT_NAME;
      const htmlVersion = cfg?.INNERTUBE_CLIENT_VERSION;
      return {
        name: typeof htmlName === 'string' ? htmlName : (typeof name === 'string' ? name : null),
        version: typeof htmlVersion === 'string' ? htmlVersion : (typeof version === 'string' ? version : null),
      };
    }

    function makeCaptionUrlCandidates(baseUrl: string): string[] {
      const out = new Set<string>();
      out.add(baseUrl);

      try {
        const u = new URL(baseUrl, location.origin);
        if (!u.searchParams.get('fmt')) {
          const json3 = new URL(u.toString());
          json3.searchParams.set('fmt', 'json3');
          out.add(json3.toString());

          const srv3 = new URL(u.toString());
          srv3.searchParams.set('fmt', 'srv3');
          out.add(srv3.toString());

          const vtt = new URL(u.toString());
          vtt.searchParams.set('fmt', 'vtt');
          out.add(vtt.toString());
        }
      } catch {
        if (!baseUrl.includes('fmt=')) {
          out.add(`${baseUrl}&fmt=json3`);
          out.add(`${baseUrl}&fmt=srv3`);
          out.add(`${baseUrl}&fmt=vtt`);
        }
      }

      return Array.from(out);
    }

    function makeTranslatedCaptionUrlCandidates(
      baseUrl: string,
      params: {
        sourceLang: string;
        trackKind: string;
        trackVssId: string;
        targetLang: string;
      },
    ): string[] {
      try {
        const url = new URL(baseUrl, location.origin);
        url.searchParams.set('tlang', params.targetLang);

        if (!url.searchParams.has('lang') && params.sourceLang) {
          url.searchParams.set('lang', params.sourceLang);
        }
        if (!url.searchParams.has('kind') && params.trackKind === 'asr') {
          url.searchParams.set('kind', 'asr');
        }
        if (!url.searchParams.has('vss_id') && params.trackVssId) {
          url.searchParams.set('vss_id', params.trackVssId);
        }
        url.searchParams.delete('fmt');

        if (isLikelySignedCaptionUrl(url)) {
          return [url.toString()];
        }

        return makeCaptionUrlCandidates(url.toString());
      } catch {
        if (baseUrl.includes('?')) {
          return [`${baseUrl}&tlang=${encodeURIComponent(params.targetLang)}`];
        }
        return [`${baseUrl}?tlang=${encodeURIComponent(params.targetLang)}`];
      }
    }

    function isLikelySignedCaptionUrl(url: URL): boolean {
      return (
        url.searchParams.has('signature')
        || url.searchParams.has('sig')
        || url.searchParams.has('lsig')
        || url.searchParams.has('expire')
        || url.searchParams.has('sparams')
      );
    }

    function normalizeYoutubeTranslationLanguage(targetLanguage: string): string {
      const normalized = targetLanguage.trim();
      if (!normalized) return 'en';

      if (/^zh[-_]hans$/i.test(normalized)) return 'zh-Hans';
      if (/^zh[-_]hant$/i.test(normalized)) return 'zh-Hant';

      return normalized.replace(/_/g, '-');
    }

    function getTrackTranslationLanguages(track: AnyObj): AnyObj[] {
      const candidates = track.translationLanguages;
      if (Array.isArray(candidates)) {
        return candidates.filter((item): item is AnyObj => isObject(item));
      }
      return [];
    }

    function getGlobalTranslationLanguages(player: PlayerElement, tracklist: AnyObj[]): AnyObj[] {
      const fromOption = player.getOption?.('captions', 'tracklistTranslationLanguages');
      if (Array.isArray(fromOption)) {
        const normalized = fromOption.filter((item): item is AnyObj => isObject(item));
        if (normalized.length > 0) return normalized;
      }

      for (const track of tracklist) {
        const langs = getTrackTranslationLanguages(track);
        if (langs.length > 0) return langs;
      }

      return [];
    }

    function readTrackLanguageCode(value: AnyObj): string {
      const candidates = [
        value.languageCode,
        value.language_code,
        value.lang,
      ];
      for (const candidate of candidates) {
        if (typeof candidate === 'string' && candidate.trim()) {
          return candidate.trim();
        }
      }
      return '';
    }

    function normalizeLanguageCodeForCompare(code: string): string {
      const normalized = code.replace(/_/g, '-').toLowerCase();
      if (normalized.startsWith('zh-hans')) return 'zh-hans';
      if (normalized.startsWith('zh-hant')) return 'zh-hant';
      return normalized.split('-')[0] ?? normalized;
    }

    function findBestTranslationLanguage(targetLanguage: string, candidates: AnyObj[]): AnyObj | null {
      if (candidates.length === 0) {
        return { languageCode: targetLanguage };
      }

      const normalizedTarget = normalizeLanguageCodeForCompare(targetLanguage);
      let exact: AnyObj | null = null;
      let baseMatch: AnyObj | null = null;

      for (const candidate of candidates) {
        const code = readTrackLanguageCode(candidate);
        if (!code) continue;
        if (code.toLowerCase() === targetLanguage.toLowerCase()) {
          exact = candidate;
          break;
        }
        if (normalizeLanguageCodeForCompare(code) === normalizedTarget) {
          baseMatch = candidate;
        }
      }

      return exact ?? baseMatch;
    }

    function buildTranslatedPlayerTrack(sourceTrack: AnyObj, translationLanguage: AnyObj, targetLanguage: string): AnyObj {
      return {
        ...sourceTrack,
        translationLanguage,
        translation_language: translationLanguage,
        tlang: targetLanguage,
      };
    }

    function rankTracksForTranslation(tracks: AnyObj[]): AnyObj[] {
      const preferredLanguages = ['en', 'ko', 'ja', 'es', 'fr', 'de', 'pt', 'it'];

      const getScore = (track: AnyObj): number => {
        const isAsr = track.kind === 'asr';
        const languageCode = typeof track.languageCode === 'string' ? track.languageCode.toLowerCase() : '';
        const baseUrl = typeof track.baseUrl === 'string' ? track.baseUrl : '';
        const isTranslatable = track.isTranslatable !== false;
        let score = 0;

        if (isTranslatable) score += 50;
        if (!isAsr) score += 20;

        const preferredIndex = preferredLanguages.indexOf(languageCode);
        if (preferredIndex !== -1) {
          score += (preferredLanguages.length - preferredIndex);
        }

        if (baseUrl.includes('lang=')) score += 5;
        if (baseUrl.includes('vss_id=')) score += 3;
        if (baseUrl.includes('/api/timedtext')) score += 2;

        return score;
      };

      return [...tracks].sort((a, b) => getScore(b) - getScore(a));
    }

    async function fetchCaptionUrl(url: string, cleanFetch: typeof fetch): Promise<Response | null> {
      try {
        return await cleanFetch(url, { credentials: 'include' });
      } catch { /* ignore */ }
      try {
        return await fetch(url, { credentials: 'include' });
      } catch {
        return null;
      }
    }

    async function getTranscriptParams(): Promise<string | null> {
      const w = window as unknown as AnyObj;
      // ytInitialData에서 먼저 시도
      const r = extractParams(w.ytInitialData);
      if (r) return r;

      // ytInitialData가 SPA에서 갱신 안 됐을 수 있으므로
      // ytd-watch-flexy 컴포넌트의 data에서 시도
      try {
        const watchFlexy = document.querySelector('ytd-watch-flexy') as (HTMLElement & { data?: AnyObj }) | null;
        if (watchFlexy?.data) {
          const p = extractParams(watchFlexy.data);
          if (p) return p;
        }
      } catch { /* */ }

      // script 태그에서 시도
      try {
        for (const s of Array.from(document.querySelectorAll('script'))) {
          const m = (s.textContent ?? '').match(/ytInitialData\s*=\s*({.+?})\s*;/);
          if (m?.[1]) {
            try { const p = extractParams(JSON.parse(m[1])); if (p) return p; } catch { /* */ }
          }
        }
      } catch { /* */ }

      // livewiki 방식: 현재 watch HTML 재조회 후 추출
      const html = await getWatchPageHtml();
      const htmlData = extractYtInitialDataFromHtml(html);
      const fromHtml = extractParams(htmlData);
      if (fromHtml) return fromHtml;

      return null;
    }

    async function getWatchPageHtml(): Promise<string | null> {
      if (watchPageHtmlCache) return watchPageHtmlCache;
      try {
        const cleanFetch = getCleanFetch();
        const resp = await cleanFetch(location.href, { credentials: 'include' });
        if (!resp.ok) {
          return null;
        }
        watchPageHtmlCache = await resp.text();
        return watchPageHtmlCache;
      } catch {
        return null;
      }
    }

    async function getCaptionTracksFromPlayerApi(videoId: string): Promise<AnyObj[] | null> {
      const context = await getInnertubeContext();
      if (!context) {
        return null;
      }

      const apiKey = getInnertubeApiKey();
      const keyParam = apiKey ? `&key=${apiKey}` : '';
      const client = getInnertubeClientInfo();
      const cleanFetch = getCleanFetch();

      try {
        const playerResp = await cleanFetch(
          `${location.origin}/youtubei/v1/player?prettyPrint=false${keyParam}`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              ...(client.name ? { 'X-Youtube-Client-Name': client.name } : {}),
              ...(client.version ? { 'X-Youtube-Client-Version': client.version } : {}),
            },
            credentials: 'include',
            body: JSON.stringify({
              videoId,
              racyCheckOk: false,
              contentCheckOk: false,
              context: normalizeInnertubeContext(context),
            }),
          },
        );
        if (!playerResp.ok) {
          try {
            const errText = await playerResp.text();
          } catch { /* ignore */ }
          return null;
        }
        const playerData = await playerResp.json() as AnyObj;
        const tracks = extractCaptionTracks(playerData);
        if (tracks?.length) {
        } else {
        }
        return tracks;
      } catch (e) {
        return null;
      }
    }

    async function getCaptionTracksFromWatchHtml(): Promise<AnyObj[] | null> {
      const html = await getWatchPageHtml();
      const playerResp = extractYtInitialPlayerResponseFromHtml(html);
      if (!playerResp) return null;
      const tracks = extractCaptionTracks(playerResp);
      if (tracks?.length) {
      }
      return tracks;
    }

    function mergeCaptionTracks(primary: AnyObj[], secondary: AnyObj[]): AnyObj[] {
      const out: AnyObj[] = [];
      const seen = new Set<string>();
      for (const t of [...primary, ...secondary]) {
        const key = `${String(t.baseUrl ?? '')}|${String(t.languageCode ?? '')}|${String(t.kind ?? '')}`;
        if (!t.baseUrl || seen.has(key)) continue;
        seen.add(key);
        out.push(t);
      }
      return out;
    }

    function extractYtcfgFromHtml(html: string | null): AnyObj | null {
      if (!html) return null;
      const m = html.match(/ytcfg\.set\s*\(\s*({[\s\S]*?})\s*\)\s*;/);
      if (!m?.[1]) return null;
      try {
        const parsed = JSON.parse(m[1]) as AnyObj;
        return isObject(parsed) ? parsed : null;
      } catch {
        return null;
      }
    }

    function extractYtInitialDataFromHtml(html: string | null): AnyObj | null {
      if (!html) return null;
      const m = html.match(/ytInitialData\s*=\s*({[\s\S]*?})\s*;/);
      if (!m?.[1]) return null;
      try {
        const parsed = JSON.parse(m[1]) as AnyObj;
        return isObject(parsed) ? parsed : null;
      } catch {
        return null;
      }
    }

    function extractYtInitialPlayerResponseFromHtml(html: string | null): AnyObj | null {
      if (!html) return null;
      const m = html.match(/ytInitialPlayerResponse\s*=\s*({[\s\S]*?})\s*;/);
      if (!m?.[1]) return null;
      try {
        const parsed = JSON.parse(m[1]) as AnyObj;
        return isObject(parsed) ? parsed : null;
      } catch {
        return null;
      }
    }

    function normalizeInnertubeContext(context: AnyObj): AnyObj {
      let ctx: AnyObj = context;
      try {
        if (typeof structuredClone === 'function') {
          ctx = structuredClone(context) as AnyObj;
        } else {
          ctx = JSON.parse(JSON.stringify(context)) as AnyObj;
        }
      } catch {
        ctx = { ...context };
      }
      const client = isObject(ctx.client) ? (ctx.client as AnyObj) : {};
      ctx.client = client;
      if (!isObject(client.configInfo)) client.configInfo = {};
      return ctx;
    }

    function extractParams(data: unknown): string | null {
      if (!isObject(data)) return null;
      const panels = (data as AnyObj).engagementPanels;
      if (!Array.isArray(panels)) return null;
      for (const p of panels) {
        if (!isObject(p)) continue;
        const r = (p as AnyObj).engagementPanelSectionListRenderer;
        if (!isObject(r) || (r as AnyObj).targetId !== 'engagement-panel-searchable-transcript') continue;
        const params = (r as AnyObj).content?.continuationItemRenderer?.continuationEndpoint?.getTranscriptEndpoint?.params;
        if (typeof params === 'string' && params.length > 0) return params;
      }
      return null;
    }

    // ─── Parsers ─────────────────────────────────────────────────

    function parseGetTranscriptResponse(data: AnyObj): TranscriptSegment[] {
      try {
        const actions = data.actions;
        if (!Array.isArray(actions)) return [];
        const segs = actions[0]?.updateEngagementPanelAction?.content?.transcriptRenderer?.content
          ?.transcriptSearchPanelRenderer?.body?.transcriptSegmentListRenderer?.initialSegments;
        if (!Array.isArray(segs)) return [];
        const out: TranscriptSegment[] = [];
        for (const item of segs) {
          const r = item?.transcriptSegmentRenderer;
          if (!r) continue;
          const runs = r.snippet?.runs;
          const text = Array.isArray(runs) ? runs.map((x: AnyObj) => x.text ?? '').join('').trim() : '';
          const startMs = Number(r.startMs); const endMs = Number(r.endMs);
          if (!text || !Number.isFinite(startMs)) continue;
          out.push({ text, offset: startMs / 1000, duration: Number.isFinite(endMs) && endMs >= startMs ? (endMs - startMs) / 1000 : 0, lang: '' });
        }
        return out;
      } catch { return []; }
    }

    // ─── Utilities ───────────────────────────────────────────────

    function normalizeSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
      const out: TranscriptSegment[] = [];
      const seen = new Set<string>();
      for (const seg of segments) {
        const text = seg.text.trim();
        if (!text) continue;
        const offset = Number.isFinite(seg.offset) ? seg.offset : 0;
        const duration = Number.isFinite(seg.duration) && seg.duration >= 0 ? seg.duration : 0;
        const key = `${Math.round(offset * 100)}|${text.replace(/\s+/g, ' ')}`;
        if (seen.has(key)) continue;
        seen.add(key);
        out.push({ text, offset, duration, lang: seg.lang });
      }
      out.sort((a, b) => a.offset - b.offset);
      for (let i = 0; i < out.length - 1; i++) {
        if (out[i].duration > 0) continue;
        const gap = out[i + 1].offset - out[i].offset;
        if (gap > 0) out[i].duration = gap;
      }
      return out;
    }

    function sleep(ms: number): Promise<void> {
      return new Promise((resolve) => setTimeout(resolve, ms));
    }

    function isObject(v: unknown): v is AnyObj {
      return typeof v === 'object' && v !== null;
    }
  },
});
